package ru.arhilab.estimate;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.print.*;import android.security.keystore.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import javax.crypto.*;import javax.crypto.spec.*;
public class MainActivity extends Activity {
 WebView web,printWeb; JSONObject db,catalog; String userId=null; byte[] exportBytes=null; char[] pendingRestorePassword=null,cloudPassword=null; CloudSync cloudClient=null; PhotoStore images=null; int failures=0,skippedBackupPhotos=0;long blockedUntil=0; String pendingProject="",pendingReceiptRef="",pendingReceiptType="",startupWarning="";
 String read(InputStream in)throws Exception {ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)b.write(buf,0,n);in.close();return b.toString("UTF-8");}
 byte[] readBytes(InputStream in)throws Exception {try(InputStream src=in;ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int n;while((n=src.read(buf))!=-1)b.write(buf,0,n);return b.toByteArray();}}
 SecretKey key()throws Exception {KeyStore k=KeyStore.getInstance("AndroidKeyStore");k.load(null);if(!k.containsAlias("arhilab-data")){KeyGenerator g=KeyGenerator.getInstance("AES","AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder("arhilab-data",KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes("GCM").setEncryptionPaddings("NoPadding").build());g.generateKey();}return (SecretKey)k.getKey("arhilab-data",null);}
 String tokenHash(byte[] token)throws Exception{return Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest(token));}
 void startSession()throws Exception{byte[] token=new byte[32];new SecureRandom().nextBytes(token);user().put("sessionHash",tokenHash(token));saveRaw();Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key());File tmp=new File(getFilesDir(),"session.tmp"),target=new File(getFilesDir(),"session.enc");try(FileOutputStream o=new FileOutputStream(tmp)){o.write(c.getIV());o.write(c.doFinal(new JSONObject().put("user",userId).put("token",Base64.getEncoder().encodeToString(token)).toString().getBytes(StandardCharsets.UTF_8)));o.getFD().sync();}if(!tmp.renameTo(target))throw new IOException("Не удалось сохранить сессию");Arrays.fill(token,(byte)0);}
 void loadSession(){File f=new File(getFilesDir(),"session.enc");if(!f.exists())return;try{byte[] all=java.nio.file.Files.readAllBytes(f.toPath());if(all.length<29)throw new IOException("Сессия повреждена");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Arrays.copyOfRange(all,0,12)));JSONObject s=new JSONObject(new String(c.doFinal(Arrays.copyOfRange(all,12,all.length)),StandardCharsets.UTF_8));JSONObject u=find(db.getJSONArray("users"),s.getString("user"));byte[] token=Base64.getDecoder().decode(s.getString("token"));if(token.length!=32||!MessageDigest.isEqual(tokenHash(token).getBytes(StandardCharsets.UTF_8),u.optString("sessionHash").getBytes(StandardCharsets.UTF_8)))throw new IOException("Сессия отозвана");userId=u.getString("id");Arrays.fill(token,(byte)0);}catch(Exception e){userId=null;f.delete();}}
 void endSession()throws Exception{user().remove("sessionHash");saveRaw();new File(getFilesDir(),"session.enc").delete();userId=null;}
 void save()throws Exception {JSONObject sync=db.optJSONObject("cloud");if(sync!=null)sync.put("dirty",true);saveRaw();}
 void saveRaw()throws Exception{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key());byte[] enc=c.doFinal(db.toString().getBytes(StandardCharsets.UTF_8));File f=new File(getFilesDir(),"data.enc"),tmp=new File(getFilesDir(),"data.tmp");try(FileOutputStream o=new FileOutputStream(tmp)){o.write(c.getIV());o.write(enc);o.getFD().sync();}if(f.exists()){File backup=new File(getFilesDir(),"data-previous.enc");java.nio.file.Files.copy(f.toPath(),backup.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);}if(!tmp.renameTo(f))throw new IOException("Не удалось сохранить данные");}
 void load()throws Exception{catalog=new JSONObject(read(getAssets().open("catalog.json")));File update=new File(getFilesDir(),"catalog-update.json");if(update.exists()){try{JSONObject latest=new JSONObject(new String(java.nio.file.Files.readAllBytes(update.toPath()),StandardCharsets.UTF_8));validateCatalog(latest);catalog=latest;}catch(Exception e){startupWarning="Обновлённый прайс не открывается; загружен встроенный каталог: "+e.getMessage();}}File f=new File(getFilesDir(),"data.enc");if(!f.exists()){db=new JSONObject().put("users",new JSONArray()).put("projects",new JSONArray());return;}byte[] all=java.nio.file.Files.readAllBytes(f.toPath());if(all.length<29)throw new IOException("Файл базы повреждён");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Arrays.copyOfRange(all,0,12)));JSONObject original=new JSONObject(new String(c.doFinal(Arrays.copyOfRange(all,12,all.length)),StandardCharsets.UTF_8));db=original;JSONObject updated=new JSONObject(original.toString());MigrationReport report=migratePhotos(updated,true);if(report.failed>0)startupWarning="Не удалось перенести "+report.failed+" фото. Объекты доступны; исходные данные фото сохранены. Первое проблемное фото: "+report.firstFailure+". Сделайте резервную копию в настройках.";if(report.migrated>0){db=updated;try{save();}catch(Exception e){db=original;startupWarning="Объекты доступны, но перенос фото пока не сохранён: "+e.getMessage()+". Не удаляйте приложение; сделайте резервную копию.";}}loadSession();}
 PhotoStore photos()throws Exception{if(images==null)images=new PhotoStore(new File(getFilesDir(),"images"),key());return images;}
 byte[] photoBytes(String data)throws Exception{String prefix="data:image/jpeg;base64,";if(!data.startsWith(prefix))throw new IOException("Некорректный формат фото");byte[] bytes=Base64.getDecoder().decode(data.substring(prefix.length()));if(bytes.length<4||(bytes[0]&255)!=255||(bytes[1]&255)!=216||(bytes[bytes.length-2]&255)!=255||(bytes[bytes.length-1]&255)!=217)throw new IOException("Повреждённый JPEG");return bytes;}
 static class MigrationReport{int migrated,failed;String firstFailure="";}
 MigrationReport migratePhotos(JSONObject database,boolean keepFailures)throws Exception{MigrationReport result=new MigrationReport();JSONArray projects=database.getJSONArray("projects");for(int i=0;i<projects.length();i++){JSONObject p=projects.getJSONObject(i);for(String arr:new String[]{"photos","estimatePhotos"}){JSONArray list=p.optJSONArray(arr);if(list==null)continue;for(int j=0;j<list.length();j++){try{JSONObject row=list.getJSONObject(j);if(!row.has("data"))continue;byte[] jpeg=photoBytes(row.getString("data"));String id=row.optString("id");if(!id.matches("[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"))id=UUID.randomUUID().toString();photos().put(id,jpeg);row.put("id",id);row.remove("data");result.migrated++;}catch(Exception e){if(!keepFailures)throw e;result.failed++;if(result.firstFailure.isEmpty())result.firstFailure=p.optString("name","Объект")+", "+(arr.equals("photos")?"фото объекта":"фото сметы")+" №"+(j+1)+" ("+e.getMessage()+")";}}}}return result;}
 JSONArray photoPayload(JSONObject p,String arr)throws Exception{JSONArray source=p.optJSONArray(arr),out=new JSONArray();if(source==null)return out;for(int i=0;i<source.length();i++){try{JSONObject row=new JSONObject(source.getJSONObject(i).toString());if(!row.has("data"))row.put("data","data:image/jpeg;base64,"+Base64.getEncoder().encodeToString(photos().get(row.getString("id"))));photoBytes(row.getString("data"));out.put(row);}catch(Exception ignored){/* Keep the record in db; skip only its unavailable image in the view/export. */}}return out;}
 JSONObject backupContent()throws Exception{JSONObject out=new JSONObject().put("format","Arhilab-1").put("team",state().getJSONArray("users"));JSONArray projects=new JSONArray();JSONArray source=db.getJSONArray("projects");skippedBackupPhotos=0;for(int i=0;i<source.length();i++){JSONObject p=new JSONObject(source.getJSONObject(i).toString());for(String arr:new String[]{"photos","estimatePhotos"})if(p.has(arr)){JSONArray original=p.getJSONArray(arr),available=photoPayload(p,arr);skippedBackupPhotos+=original.length()-available.length();p.put(arr,available);}projects.put(p);}return out.put("projects",projects).put("catalog",catalog);}
 public void onCreate(Bundle b){super.onCreate(b);try{load();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Ошибка открытия базы").setMessage("Данные не перезаписаны. "+e.getMessage()).setPositiveButton("Закрыть",(d,w)->finish()).show();return;}web=new WebView(this);web.setBackgroundColor(0xfff2f3ef);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setDomStorageEnabled(false);web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}public void onPageFinished(WebView v,String url){if(!startupWarning.isEmpty()){String message=startupWarning;startupWarning="";new AlertDialog.Builder(MainActivity.this).setTitle("Проверка фотографий").setMessage(message).setPositiveButton("Понятно",null).show();}}});web.setWebChromeClient(new WebChromeClient());web.addJavascriptInterface(new Bridge(),"Native");setContentView(web);web.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(in.getSystemWindowInsetLeft(),in.getSystemWindowInsetTop(),in.getSystemWindowInsetRight(),in.getSystemWindowInsetBottom());return in.consumeSystemWindowInsets();});web.loadUrl("file:///android_asset/index.html");}
 JSONObject find(JSONArray a,String id)throws Exception{for(int i=0;i<a.length();i++)if(a.getJSONObject(i).optString("id").equals(id))return a.getJSONObject(i);throw new Exception("Запись не найдена");}
 JSONObject user()throws Exception{if(userId==null)throw new Exception("Войдите в приложение");return find(db.getJSONArray("users"),userId);}
 String role()throws Exception{return user().getString("role");}
 void admin()throws Exception{if(!role().equals("admin"))throw new Exception("Доступно администратору");}
 void editor()throws Exception{if(role().equals("worker"))throw new Exception("Недостаточно прав");}
 String hash(String pw,String salt)throws Exception{PBEKeySpec p=new PBEKeySpec(pw.toCharArray(),Base64.getDecoder().decode(salt),120000,256);return Base64.getEncoder().encodeToString(SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(p).getEncoded());}
 void password(JSONObject u,String pw)throws Exception{if(pw.length()<8)throw new Exception("Пароль: минимум 8 символов");byte[] b=new byte[16];new SecureRandom().nextBytes(b);String salt=Base64.getEncoder().encodeToString(b);u.put("salt",salt).put("hash",hash(pw,salt));}
 JSONObject safeUser(JSONObject u)throws Exception{return new JSONObject().put("id",u.getString("id")).put("name",u.getString("name")).put("login",u.getString("login")).put("role",u.getString("role"));}
 JSONObject project(String id)throws Exception{JSONObject p=find(db.getJSONArray("projects"),id);if(role().equals("worker")&&!p.optString("assigned").equals(userId))throw new Exception("Объект не назначен вам");return p;}
 void stripCosts(JSONObject p)throws Exception{for(String k:new String[]{"deliveryCost","overhead","otherCost","purchases"})p.remove(k);for(String arr:new String[]{"lines","materials"}){JSONArray a=p.optJSONArray(arr);if(a!=null)for(int i=0;i<a.length();i++){a.getJSONObject(i).remove("cost");a.getJSONObject(i).remove("materialCost");}}JSONArray visible=new JSONArray();JSONArray payments=p.optJSONArray("payments");if(payments!=null)for(int i=0;i<payments.length();i++)if(payments.getJSONObject(i).optString("kind").equals("income"))visible.put(payments.getJSONObject(i));p.put("payments",visible);}
 JSONObject state()throws Exception{String r=role();JSONObject out=new JSONObject().put("user",safeUser(user()));JSONArray ps=new JSONArray();for(int i=0;i<db.getJSONArray("projects").length();i++){JSONObject p=new JSONObject(db.getJSONArray("projects").getJSONObject(i).toString());if(r.equals("worker")){if(!p.optString("assigned").equals(userId))continue;JSONObject q=new JSONObject();for(String k:new String[]{"id","name","address","status","assigned","tasks","notes","photos"})if(p.has(k))q.put(k,p.get(k));p=q;}else if(!r.equals("admin"))stripCosts(p);if(!r.equals("admin")){JSONArray source=p.optJSONArray("photos"),visible=new JSONArray();if(source!=null)for(int j=0;j<source.length();j++)if(!source.getJSONObject(j).has("purchaseRef"))visible.put(source.getJSONObject(j));p.put("photos",visible);}ps.put(p);}out.put("projects",ps);JSONArray us=new JSONArray();if(!r.equals("worker"))for(int i=0;i<db.getJSONArray("users").length();i++)us.put(safeUser(db.getJSONArray("users").getJSONObject(i)));out.put("users",us);if(r.equals("admin")){JSONObject info=db.optJSONObject("cloud");out.put("cloud",new JSONObject().put("url",info==null?"":info.optString("url")).put("revision",info==null?-1:info.optInt("revision",-1)).put("dirty",info!=null&&info.optBoolean("dirty")).put("connected",cloudClient!=null));}return out;}
 JSONObject visibleCatalog(int percent)throws Exception{String r=role();if(r.equals("worker"))return new JSONObject().put("works",new JSONArray()).put("materials",new JSONArray());JSONObject c=new JSONObject(catalog.toString());for(int i=0;i<c.getJSONArray("works").length();i++){JSONObject w=c.getJSONArray("works").getJSONObject(i);JSONObject tiers=w.optJSONObject("tiers");if(tiers!=null)for(String tier:new String[]{"economy","standard","premium"}){JSONObject kit=tiers.getJSONObject(tier);kit.put("materialPrice",MaterialMarkup.price(kit.getDouble("materialCost"),percent));}}for(int i=0;i<c.getJSONArray("materials").length();i++){JSONObject m=c.getJSONArray("materials").getJSONObject(i);m.put("price",MaterialMarkup.price(m.getDouble("cost"),percent));}if(!r.equals("admin")){for(String arr:new String[]{"works","materials"})for(int i=0;i<c.getJSONArray(arr).length();i++){c.getJSONArray(arr).getJSONObject(i).remove("cost");JSONObject item=c.getJSONArray(arr).getJSONObject(i);item.remove("materialCost");JSONObject tiers=item.optJSONObject("tiers");if(tiers!=null)for(String tier:new String[]{"economy","standard","premium"})tiers.getJSONObject(tier).remove("materialCost");}}return c;}
 double num(JSONObject a,String k)throws Exception{double n=a.optDouble(k,0);if(!Double.isFinite(n)||n<0||n>1e12)throw new Exception("Некорректное число: "+k);return n;}
 String required(JSONObject a,String k)throws Exception{String s=a.optString(k).trim();if(s.isEmpty()||s.length()>5000)throw new Exception("Заполните поле: "+k);return s;}
 void validateCatalog(JSONObject c)throws Exception{if(!"ArhilabCatalog-2".equals(c.optString("format")))throw new Exception("Формат прайса не поддерживается");JSONArray works=c.getJSONArray("works"),materials=c.getJSONArray("materials");if(works.length()<1||materials.length()<1||works.length()>10000||materials.length()>10000)throw new Exception("Каталог пуст или слишком велик");Set<String> ids=new HashSet<>(),keys=new HashSet<>();for(int i=0;i<materials.length();i++){JSONObject m=materials.getJSONObject(i);String id=m.getString("id"),name=m.getString("name");if(id.isEmpty()||name.isEmpty()||!ids.add(id))throw new Exception("Повтор или пустой SKU");double cost=m.getDouble("cost");if(!Double.isFinite(cost)||cost<0||cost>1e12)throw new Exception("Некорректная закупка SKU");}for(int i=0;i<works.length();i++){JSONObject w=works.getJSONObject(i);if(!keys.add(w.getString("key"))||w.getString("id").isEmpty())throw new Exception("Повтор работы");for(String tier:new String[]{"economy","standard","premium"}){JSONObject kit=w.getJSONObject("tiers").getJSONObject(tier);double cost=kit.getDouble("materialCost");if(!Double.isFinite(cost)||cost<0||cost>1e12)throw new Exception("Некорректная цена комплекта");JSONArray refs=kit.getJSONArray("materialIds");for(int j=0;j<refs.length();j++)if(!ids.contains(refs.getString(j)))throw new Exception("Материал комплекта не найден: "+refs.getString(j));if(refs.length()==0&&cost!=0)throw new Exception("Комплект без товаров содержит стоимость");}}}
 JSONObject matchingWork(JSONObject l)throws Exception{JSONArray works=catalog.getJSONArray("works");for(int i=0;i<works.length();i++){JSONObject w=works.getJSONObject(i);if(!l.optString("key").isEmpty()&&l.optString("key").equals(w.optString("key")))return w;if(l.optString("name").equals(w.optString("name"))&&l.optString("category").equals(w.optString("category")))return w;}throw new Exception("Работа отсутствует в каталоге");}
 void setTier(JSONObject l,JSONObject w,String tier,int markup)throws Exception{if(!Arrays.asList("economy","standard","premium").contains(tier))throw new Exception("Неверный класс материалов");JSONObject kit=w.getJSONObject("tiers").getJSONObject(tier);JSONArray ids=kit.getJSONArray("materialIds"),names=new JSONArray();for(int i=0;i<ids.length();i++)names.put(find(catalog.getJSONArray("materials"),ids.getString(i)).getString("name"));l.put("materialTier",tier).put("materials",names).put("materialNote",kit.optString("note")).put("materialCost",kit.getDouble("materialCost")).put("materialPrice",MaterialMarkup.price(kit.getDouble("materialCost"),markup)).put("autoMaterial",ids.length()>0);l.remove("tiers");l.remove("kitOverrides");}
 void refreshKitOverrides(JSONObject l,JSONObject w,int markup)throws Exception{JSONObject kit=w.getJSONObject("tiers").getJSONObject(l.optString("materialTier","standard")),overrides=l.optJSONObject("kitOverrides");JSONArray ids=kit.getJSONArray("materialIds"),names=new JSONArray();double cost=kit.getDouble("materialCost");for(int i=0;i<ids.length();i++){String base=ids.getString(i);JSONObject original=find(catalog.getJSONArray("materials"),base),override=overrides==null?null:overrides.optJSONObject(base);if(override==null){names.put(original.getString("name"));continue;}JSONObject replacement=find(catalog.getJSONArray("materials"),override.getString("sku"));double qty=override.getDouble("qty");cost+=(replacement.getDouble("cost")-original.getDouble("cost"))*qty;names.put(replacement.getString("name"));}if(cost<0)throw new Exception("Замена делает стоимость комплекта отрицательной");l.put("materials",names).put("materialCost",Math.round(cost*100)/100.0).put("materialPrice",MaterialMarkup.price(cost,markup));}
 void storeCatalog(JSONObject updated)throws Exception{validateCatalog(updated);File target=new File(getFilesDir(),"catalog-update.json"),tmp=new File(getFilesDir(),"catalog-update.tmp");try(FileOutputStream out=new FileOutputStream(tmp)){out.write(updated.toString().getBytes(StandardCharsets.UTF_8));out.getFD().sync();}if(target.exists())java.nio.file.Files.copy(target.toPath(),new File(getFilesDir(),"catalog-previous.json").toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);else java.nio.file.Files.write(new File(getFilesDir(),"catalog-previous.json").toPath(),catalog.toString().getBytes(StandardCharsets.UTF_8));if(!tmp.renameTo(target))throw new IOException("Не удалось сохранить прайс");catalog=updated;java.nio.file.Files.write(new File(getFilesDir(),"catalog-updated.txt").toPath(),new Date().toString().getBytes(StandardCharsets.UTF_8));JSONObject meta=db.optJSONObject("cloud");if(meta!=null){meta.put("dirty",true);saveRaw();}}
 void closeCloud(){cloudClient=null;if(cloudPassword!=null){Arrays.fill(cloudPassword,'\0');cloudPassword=null;}}
 JSONObject remoteData(CloudSync.Vault vault,char[] password)throws Exception{if(vault.ciphertext==null)throw new IOException("На сервере пока нет данных. Сначала отправьте данные с первого телефона.");byte[] decoded;try{decoded=BackupCrypto.decrypt(vault.ciphertext,password);}catch(javax.crypto.AEADBadTagException e){throw new IOException("Пароль не подходит к зашифрованной базе сервера");}JSONObject data=new JSONObject(new String(decoded,StandardCharsets.UTF_8));if(!data.optString("format").equals("Arhilab-1"))throw new IOException("Неизвестный формат базы на сервере");validateBackup(data);return data;}
 void applyRemote(JSONObject data,CloudSync.Vault vault,CloudSync connection,boolean newDevice,char[] password)throws Exception{JSONObject previous=db;String previousUser=userId;try{JSONObject next=newDevice?new JSONObject().put("users",new JSONArray()):new JSONObject(db.toString());if(newDevice){JSONObject admin=new JSONObject().put("id",UUID.randomUUID().toString()).put("name","Администратор").put("login","admin").put("role","admin");password(admin,new String(password));next.getJSONArray("users").put(admin);userId=admin.getString("id");}JSONArray projects=new JSONArray(data.getJSONArray("projects").toString());for(int i=0;i<projects.length();i++){JSONObject p=projects.getJSONObject(i);for(String arr:new String[]{"photos","estimatePhotos"}){JSONArray rows=p.optJSONArray(arr);if(rows!=null)for(int j=0;j<rows.length();j++)rows.getJSONObject(j).put("id",UUID.randomUUID().toString());}}JSONObject importedCatalog=data.optJSONObject("catalog");if(importedCatalog!=null)validateCatalog(importedCatalog);next.put("projects",projects).put("cloud",new JSONObject().put("url",connection.url).put("revision",vault.revision).put("dirty",false));migratePhotos(next,false);if(importedCatalog!=null)storeCatalog(importedCatalog);db=next;saveRaw();}catch(Exception e){db=previous;userId=previousUser;throw e;}}
 void beginBackupPicker(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/octet-stream").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"Arhilab-protected-backup.arhilab");startActivityForResult(i,11);}
 class Bridge {
 @JavascriptInterface public synchronized String call(String action,String raw){JSONObject before=null;try{JSONObject a=new JSONObject(raw);JSONObject result=new JSONObject();
 if(action.equals("session")){if(userId==null)return "{\"ok\":true,\"active\":false}";return new JSONObject().put("ok",true).put("active",true).put("state",state()).toString();}
 if(action.equals("status"))return new JSONObject().put("ok",true).put("setup",db.getJSONArray("users").length()==0).toString();
 if(action.equals("setup")){if(db.getJSONArray("users").length()!=0)throw new Exception("Администратор уже создан");JSONObject u=new JSONObject().put("id",UUID.randomUUID().toString()).put("name",required(a,"name")).put("login","admin").put("role","admin");password(u,required(a,"password"));db.getJSONArray("users").put(u);save();userId=u.getString("id");startSession();return new JSONObject().put("ok",true).put("state",state()).toString();}
 if(action.equals("cloudLogin")){if(db.getJSONArray("users").length()!=0)throw new Exception("На этом телефоне уже есть база. Войдите локально и подключите сервер в настройках.");char[] secret=required(a,"password").toCharArray();try{if(secret.length<12)throw new Exception("Пароль сервера: минимум 12 символов");CloudSync candidate=new CloudSync(required(a,"url"));candidate.login(required(a,"login"),secret);CloudSync.Vault vault=candidate.fetch();JSONObject contents=remoteData(vault,secret);applyRemote(contents,vault,candidate,true,secret);cloudClient=candidate;cloudPassword=secret;secret=null;startSession();return new JSONObject().put("ok",true).put("state",state()).toString();}finally{if(secret!=null)Arrays.fill(secret,'\0');}}
 if(action.equals("login")){if(System.currentTimeMillis()<blockedUntil)throw new Exception("Слишком много попыток. Повторите через минуту");JSONObject match=null;for(int i=0;i<db.getJSONArray("users").length();i++){JSONObject u=db.getJSONArray("users").getJSONObject(i);if(u.getString("login").equals(a.optString("login"))&&MessageDigest.isEqual(hash(a.optString("password"),u.getString("salt")).getBytes(StandardCharsets.UTF_8),u.getString("hash").getBytes(StandardCharsets.UTF_8)))match=u;}if(match==null){failures++;if(failures>=5){blockedUntil=System.currentTimeMillis()+60000;failures=0;}throw new Exception("Неверный логин или пароль");}userId=match.getString("id");startSession();failures=0;return new JSONObject().put("ok",true).put("state",state()).toString();}
 user();before=new JSONObject(db.toString());
 switch(action){
 case "logout":endSession();closeCloud();return "{\"ok\":true}";
 case "state":break;
 case "cloudConnect":{admin();char[] secret=required(a,"password").toCharArray();try{if(secret.length<12)throw new Exception("Пароль сервера: минимум 12 символов");CloudSync candidate=new CloudSync(required(a,"url"));JSONObject old=db.optJSONObject("cloud");if(old!=null&&!old.optString("url").equals(candidate.url))throw new Exception("Устройство уже связано с другим сервером");candidate.login(required(a,"login"),secret);CloudSync.Vault vault=candidate.fetch();if(old==null){db.put("cloud",new JSONObject().put("url",candidate.url).put("revision",vault.ciphertext==null?0:-1).put("dirty",true));saveRaw();}closeCloud();cloudClient=candidate;cloudPassword=secret;secret=null;result.put("serverRevision",vault.revision);break;}finally{if(secret!=null)Arrays.fill(secret,'\0');}}
 case "cloudPush":{admin();if(cloudClient==null||cloudPassword==null)throw new Exception("Сначала подключитесь к серверу");JSONObject meta=db.getJSONObject("cloud");int revision=meta.optInt("revision",-1);if(revision<0)throw new Exception("На сервере уже есть база. Сначала получите её или используйте новый сервер.");JSONObject content=backupContent();if(skippedBackupPhotos>0)throw new Exception("Недоступно фото: "+skippedBackupPhotos+". Исправьте фото, прежде чем отправлять копию в общую базу.");byte[] encrypted=BackupCrypto.encrypt(content.toString().getBytes(StandardCharsets.UTF_8),cloudPassword);int updated=cloudClient.push(revision,encrypted);meta.put("revision",updated).put("dirty",false);saveRaw();result.put("serverRevision",updated);break;}
 case "cloudPull":{admin();if(cloudClient==null||cloudPassword==null)throw new Exception("Сначала подключитесь к серверу");CloudSync.Vault vault=cloudClient.fetch();JSONObject contents=remoteData(vault,cloudPassword);JSONObject meta=db.optJSONObject("cloud");if(db.getJSONArray("projects").length()>0&&!a.optBoolean("replace"))throw new Exception("Получение заменит локальные объекты. Сначала сохраните резервную копию и подтвердите замену.");if(meta!=null&&meta.optInt("revision",-1)>vault.revision)throw new Exception("Версия сервера старее локальной. Обратитесь к администратору сервера.");applyRemote(contents,vault,cloudClient,false,cloudPassword);result.put("serverRevision",vault.revision);break;}
 case "importCatalog":{admin();runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,16);});break;}
 case "catalogInfo":{editor();File updated=new File(getFilesDir(),"catalog-updated.txt");result.put("skuCount",catalog.getJSONArray("materials").length()).put("version",catalog.optString("sourceSha256",catalog.optString("version","Встроенный"))).put("updated",updated.exists()?new String(java.nio.file.Files.readAllBytes(updated.toPath()),StandardCharsets.UTF_8):"Встроенный каталог").put("source",catalog.optString("source","Встроенный прайс"));break;}
 case "catalog":result.put("catalog",visibleCatalog(a.optString("project").isEmpty()?8:project(a.getString("project")).optInt("materialMarkup",8)));break;
 case "photoData":{JSONObject p=project(a.getString("project"));String arr=a.getString("array");if(!arr.equals("photos")&&!arr.equals("estimatePhotos"))throw new Exception("Неверный раздел фото");if(arr.equals("estimatePhotos"))editor();JSONArray available=photoPayload(p,arr),all=p.optJSONArray(arr);if(!role().equals("admin")&&arr.equals("photos")){JSONArray visible=new JSONArray();for(int i=0;i<available.length();i++)if(!available.getJSONObject(i).has("purchaseRef"))visible.put(available.getJSONObject(i));available=visible;}result.put("photos",available).put("missingPhotos",all==null?0:all.length()-available.length());break;}
 case "password":if(!hash(a.optString("old"),user().getString("salt")).equals(user().getString("hash")))throw new Exception("Текущий пароль неверен");password(user(),required(a,"password"));startSession();break;
 case "user":{admin();String login=required(a,"login");for(int i=0;i<db.getJSONArray("users").length();i++)if(db.getJSONArray("users").getJSONObject(i).getString("login").equals(login))throw new Exception("Логин уже занят");String r=a.optString("role");if(!r.equals("manager")&&!r.equals("worker"))throw new Exception("Выберите роль");JSONObject u=new JSONObject().put("id",UUID.randomUUID().toString()).put("login",login).put("name",required(a,"name")).put("role",r);password(u,required(a,"password"));db.getJSONArray("users").put(u);save();break;}
 case "resetPassword":{admin();JSONObject target=find(db.getJSONArray("users"),a.getString("id"));password(target,required(a,"password"));target.remove("sessionHash");if(target.getString("id").equals(userId))endSession();else save();break;}
 case "project":{editor();JSONObject p;if(a.optString("id").isEmpty()){p=new JSONObject().put("id",UUID.randomUUID().toString()).put("materialMarkup",8);for(String k:new String[]{"lines","materials","tasks","payments","notes","photos","estimatePhotos"})p.put(k,new JSONArray());db.getJSONArray("projects").put(p);}else p=project(a.getString("id"));p.put("name",required(a,"name")).put("address",a.optString("address")).put("client",a.optString("client")).put("status",a.optString("status","Новый")).put("assigned",a.optString("assigned"));for(String k:new String[]{"delivery","discount"})p.put(k,num(a,k));if(role().equals("admin"))for(String k:new String[]{"deliveryCost","overhead","otherCost"})p.put(k,num(a,k));save();result.put("projectId",p.getString("id"));break;}
 case "materialMarkup":{editor();JSONObject p=project(a.getString("project"));int percent=MaterialMarkup.validate(a.getInt("percent"));JSONArray ms=p.getJSONArray("materials");for(int i=0;i<ms.length();i++){JSONObject m=ms.getJSONObject(i);if(m.has("cost"))m.put("price",MaterialMarkup.price(m.getDouble("cost"),percent));}JSONArray lines=p.getJSONArray("lines");for(int i=0;i<lines.length();i++){JSONObject l=lines.getJSONObject(i);if(l.has("materialCost"))l.put("materialPrice",MaterialMarkup.price(l.getDouble("materialCost"),percent));}p.put("materialMarkup",percent);save();break;}
 case "estimateAddress":{editor();JSONObject p=project(a.getString("project"));String address=required(a,"address");p.put("address",address);save();break;}
 case "estimatePhoto":{editor();JSONObject p=project(a.getString("project"));if(p.optJSONArray("estimatePhotos")!=null&&p.getJSONArray("estimatePhotos").length()>=12)throw new Exception("Не более 12 фото в одной смете");pendingProject=p.getString("id");runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,14);});break;}
 case "removeEstimatePhoto":{editor();JSONObject p=project(a.getString("project"));JSONArray photos=p.optJSONArray("estimatePhotos");if(photos==null)throw new Exception("Фото не найдено");boolean removed=false;for(int i=0;i<photos.length();i++)if(photos.getJSONObject(i).optString("id").equals(a.optString("id"))){photos.remove(i);removed=true;break;}if(!removed)throw new Exception("Фото не найдено");save();try{photos().delete(a.getString("id"));}catch(Exception ignored){}break;}
 case "line":{editor();JSONObject p=project(a.getString("project")),w=find(catalog.getJSONArray("works"),a.getString("work"));double qty=num(a,"qty"),coef=num(a,"coef");if(qty==0||coef==0)throw new Exception("Объём и коэффициент должны быть больше нуля");JSONObject l=new JSONObject(w.toString()).put("id",UUID.randomUUID().toString()).put("qty",qty).put("coef",coef).put("price",num(a,"price"));setTier(l,w,a.optString("tier","standard"),p.optInt("materialMarkup",8));if(!a.optBoolean("autoMaterial"))l.put("autoMaterial",false);if(role().equals("admin"))l.put("cost",num(a,"cost"));if(a.optBoolean("extra"))l.put("extra",true).put("extraStatus","Создано").put("createdBy",user().getString("name")).put("createdAt",System.currentTimeMillis());p.getJSONArray("lines").put(l);save();break;}
 case "lineTier":{editor();JSONObject p=project(a.getString("project")),l=find(p.getJSONArray("lines"),a.getString("id")),w=matchingWork(l);setTier(l,w,a.getString("tier"),p.optInt("materialMarkup",8));save();break;}
 case "extraStatus":{editor();JSONObject l=find(project(a.getString("project")).getJSONArray("lines"),a.getString("id"));if(!l.optBoolean("extra"))throw new Exception("Это не дополнительная работа");String status=a.getString("status");if(!Arrays.asList("Создано","Отправлено на согласование","Согласовано","Выполняется","Выполнено","Оплачено","Отклонено").contains(status))throw new Exception("Неизвестный статус допработы");if(status.equals("Согласовано")&&!role().equals("admin"))throw new Exception("Согласование доступно администратору");l.put("extraStatus",status);if(status.equals("Согласовано"))l.put("approvedBy",user().getString("name"));save();break;}
 case "kitReplace":{editor();JSONObject p=project(a.getString("project")),l=find(p.getJSONArray("lines"),a.getString("id")),w=matchingWork(l);String base=a.getString("base"),tier=l.optString("materialTier","standard");JSONArray ids=w.getJSONObject("tiers").getJSONObject(tier).getJSONArray("materialIds");boolean found=false;for(int i=0;i<ids.length();i++)if(base.equals(ids.getString(i)))found=true;if(!found)throw new Exception("Материал отсутствует в комплекте");JSONObject overrides=l.optJSONObject("kitOverrides");if(overrides==null){overrides=new JSONObject();l.put("kitOverrides",overrides);}String sku=a.optString("sku",base);if(sku.equals(base))overrides.remove(base);else{find(catalog.getJSONArray("materials"),sku);double qty=num(a,"qty");if(qty<=0)throw new Exception("Укажите точный расход заменяемого материала на единицу работы");overrides.put(base,new JSONObject().put("sku",sku).put("qty",qty));}refreshKitOverrides(l,w,p.optInt("materialMarkup",8));save();break;}
 case "purchase":{admin();JSONObject p=project(a.getString("project"));String ref=required(a,"ref");if(ref.length()>150)throw new Exception("Некорректная позиция");boolean found=false;JSONArray lines=p.getJSONArray("lines");for(int i=0;i<lines.length();i++){JSONObject l=lines.getJSONObject(i);if(!ref.startsWith(l.optString("id")+":"))continue;String base=ref.substring(l.getString("id").length()+1);JSONArray ids=matchingWork(l).getJSONObject("tiers").getJSONObject(l.optString("materialTier","standard")).getJSONArray("materialIds");for(int j=0;j<ids.length();j++)if(base.equals(ids.getString(j)))found=true;}JSONArray manual=p.getJSONArray("materials");for(int i=0;i<manual.length();i++)if(ref.equals(manual.getJSONObject(i).optString("id")))found=true;if(!found)throw new Exception("Позиция сметы не найдена");double qty=num(a,"qty"),pack=num(a,"pack"),reserve=num(a,"reserve"),actual=num(a,"actual");if(pack<=0||reserve>100)throw new Exception("Проверьте упаковку и запас");String status=a.optString("status");if(!Arrays.asList("Нужно купить","Заказано","Оплачено","Доставлено","На объекте","Возврат").contains(status))throw new Exception("Неверный статус");JSONObject entries=p.optJSONObject("purchases");if(entries==null){entries=new JSONObject();p.put("purchases",entries);}entries.put(ref,new JSONObject().put("qty",qty).put("pack",pack).put("reserve",reserve).put("actual",actual).put("actualEntered",a.optBoolean("actualEntered")).put("status",status).put("updated",System.currentTimeMillis()));save();break;}
 case "material":{editor();JSONObject p=project(a.getString("project")),m=find(catalog.getJSONArray("materials"),a.getString("material"));double q=num(a,"qty");if(q==0)throw new Exception("Количество должно быть больше нуля");JSONObject l=new JSONObject(m.toString()).put("id",UUID.randomUUID().toString()).put("qty",q);double cost=role().equals("admin")?num(a,"cost"):m.getDouble("cost");l.put("cost",cost).put("price",MaterialMarkup.price(cost,p.optInt("materialMarkup",8)));p.getJSONArray("materials").put(l);save();break;}
 case "remove":{editor();String arr=a.getString("array");if(!Arrays.asList("lines","materials","payments","tasks").contains(arr))throw new Exception("Удаление запрещено");if(arr.equals("payments"))admin();JSONArray ar=project(a.getString("project")).getJSONArray(arr);for(int i=0;i<ar.length();i++)if(ar.getJSONObject(i).getString("id").equals(a.getString("id"))){ar.remove(i);break;}save();break;}
 case "payment":{admin();JSONObject p=project(a.getString("project"));double n=num(a,"amount");if(n==0)throw new Exception("Сумма должна быть больше нуля");p.getJSONArray("payments").put(new JSONObject().put("id",UUID.randomUUID().toString()).put("amount",n).put("kind",a.optString("kind").equals("expense")?"expense":"income").put("date",required(a,"date")).put("note",a.optString("note")).put("type",a.optString("type","Платёж за этап")).put("planDate",a.optString("planDate")).put("paid",num(a,"paid")));save();break;}
 case "paymentUpdate":{admin();JSONObject x=find(project(a.getString("project")).getJSONArray("payments"),a.getString("id"));double paid=num(a,"paid");if(paid>x.getDouble("amount"))throw new Exception("Оплата превышает сумму платежа");x.put("paid",paid).put("planDate",a.optString("planDate")).put("actualDate",a.optString("actualDate"));save();break;}
 case "task":{editor();JSONObject p=project(a.getString("project"));p.getJSONArray("tasks").put(new JSONObject().put("id",UUID.randomUUID().toString()).put("name",required(a,"name")).put("done",false).put("progress",0).put("status","Не начато").put("planDate",a.optString("planDate")).put("responsible",a.optString("responsible")).put("comment",a.optString("comment")));save();break;}
 case "taskUpdate":{JSONObject t=find(project(a.getString("project")).getJSONArray("tasks"),a.getString("id"));int progress=a.getInt("progress");if(progress<0||progress>100)throw new Exception("Прогресс должен быть от 0 до 100%");String status=a.getString("status");if(!Arrays.asList("Не начато","В работе","Приостановлено","Завершено").contains(status))throw new Exception("Неверный статус этапа");t.put("progress",progress).put("status",status).put("done",status.equals("Завершено")).put("planDate",a.optString("planDate")).put("actualDate",a.optString("actualDate")).put("responsible",a.optString("responsible")).put("comment",a.optString("comment"));save();break;}
 case "taskDone":{JSONObject p=project(a.getString("project"));find(p.getJSONArray("tasks"),a.getString("id")).put("done",a.getBoolean("done"));save();break;}
 case "note":{JSONObject p=project(a.getString("project"));p.getJSONArray("notes").put(new JSONObject().put("text",required(a,"text")).put("author",user().getString("name")).put("date",new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.ROOT).format(new Date())));save();break;}
 case "photo":{project(a.getString("project"));pendingProject=a.getString("project");runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,13);});break;}
 case "purchasePhoto":{admin();JSONObject p=project(a.getString("project"));String ref=required(a,"ref");JSONObject purchases=p.optJSONObject("purchases");if(purchases==null||!purchases.has(ref))throw new Exception("Сначала сохраните позицию закупки");String type=a.getString("type");if(!Arrays.asList("Чек","Накладная","Счёт","Документ поставщика").contains(type))throw new Exception("Неверный тип документа");pendingProject=p.getString("id");pendingReceiptRef=ref;pendingReceiptType=type;runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,18);});break;}
 case "backupInfo":{admin();File f=new File(getFilesDir(),"data-previous.enc");result.put("available",f.exists()).put("updated",f.exists()?new Date(f.lastModified()).toString():"");break;}
 case "restoreAuto":{admin();File f=new File(getFilesDir(),"data-previous.enc");if(!f.exists())throw new Exception("Локальной автокопии пока нет");byte[] all=java.nio.file.Files.readAllBytes(f.toPath());if(all.length<29)throw new Exception("Автокопия повреждена");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Arrays.copyOfRange(all,0,12)));JSONObject restored=new JSONObject(new String(c.doFinal(Arrays.copyOfRange(all,12,all.length)),StandardCharsets.UTF_8));find(restored.getJSONArray("users"),userId);restored.getJSONArray("projects");db=restored;saveRaw();startSession();break;}
 case "backup":{admin();char[] pw=required(a,"password").toCharArray();try{exportBytes=BackupCrypto.encrypt(backupContent().toString().getBytes(StandardCharsets.UTF_8),pw);}finally{Arrays.fill(pw,'\0');}int skipped=skippedBackupPhotos;runOnUiThread(()->{if(skipped>0)new AlertDialog.Builder(MainActivity.this).setTitle("Не все фото доступны").setMessage("Не удалось прочитать "+skipped+" фото. Они останутся в базе телефона, но не войдут в эту копию. Сохранить остальные данные и доступные фото?").setNegativeButton("Отмена",(d,w)->exportBytes=null).setPositiveButton("Сохранить",(d,w)->beginBackupPicker()).show();else beginBackupPicker();});break;}
 case "restore":case "verifyBackup":{admin();char[] pw=required(a,"password").toCharArray();if(pw.length<12)throw new Exception("Введите пароль резервной копии (от 12 символов)");if(pendingRestorePassword!=null)Arrays.fill(pendingRestorePassword,'\0');pendingRestorePassword=pw;int request=action.equals("verifyBackup")?15:12;runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,request);});break;}
 case "print":{editor();String logo="data:image/png;base64,"+Base64.getEncoder().encodeToString(readBytes(getAssets().open("logo.png")));final String html=a.getString("html").replace("ARHILAB_LOGO_PLACEHOLDER",logo);runOnUiThread(()->{printWeb=new WebView(MainActivity.this);printWeb.getSettings().setJavaScriptEnabled(false);printWeb.getSettings().setAllowFileAccess(false);printWeb.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String url){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print("Arhilab-КП",v.createPrintDocumentAdapter("Arhilab-КП"),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}});printWeb.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);});break;}
 default:throw new Exception("Неизвестная операция");}
 result.put("ok",true).put("state",state());return result.toString();
 }catch(Exception e){if(before!=null)db=before;return "{\"ok\":false,\"error\":"+JSONObject.quote(e.getMessage()==null?"Ошибка операции":e.getMessage())+"}";}}
 }
 void notifyJs(String s){web.evaluateJavascript("alert("+JSONObject.quote(s)+"); refresh();",null);}
 JSONObject readBackup(Uri uri)throws Exception{byte[] contents=readBytes(getContentResolver().openInputStream(uri));if(BackupCrypto.isEncrypted(contents)){if(pendingRestorePassword==null)throw new Exception("Введите пароль копии");try{contents=BackupCrypto.decrypt(contents,pendingRestorePassword);}catch(javax.crypto.AEADBadTagException e){throw new Exception("Неверный пароль или повреждённая копия");}}else if(contents.length==0||contents[0]!='{')throw new Exception("Неизвестный формат файла");JSONObject backup=new JSONObject(new String(contents,StandardCharsets.UTF_8));if(!backup.optString("format").equals("Arhilab-1"))throw new Exception("Неизвестный формат копии");return backup;}
 int validateBackup(JSONObject backup)throws Exception{int imageCount=0;JSONArray imported=backup.getJSONArray("projects");for(int i=0;i<imported.length();i++){JSONObject p=imported.getJSONObject(i);if(!p.getString("id").matches("[a-f0-9-]{36}"))throw new Exception("Некорректный ID объекта");p.getString("name");for(String arr:new String[]{"lines","materials","tasks","payments","notes","photos","estimatePhotos"}){JSONArray rows=arr.equals("estimatePhotos")?p.optJSONArray(arr):p.getJSONArray(arr);if(rows==null)continue;for(int j=0;j<rows.length();j++){JSONObject row=rows.getJSONObject(j);if(row.has("id")&&!row.getString("id").matches("[a-f0-9-]{36}"))throw new Exception("Некорректный ID записи");if(arr.equals("photos")||arr.equals("estimatePhotos")){photoBytes(row.optString("data"));imageCount++;}}}}return imageCount;}
 protected void onActivityResult(int req,int result,Intent intent){
  super.onActivityResult(req,result,intent);
  if(result!=RESULT_OK||intent==null){if(req==11)exportBytes=null;if((req==12||req==15)&&pendingRestorePassword!=null){Arrays.fill(pendingRestorePassword,'\0');pendingRestorePassword=null;}return;}
  try{
   if(req==11){admin();if(exportBytes==null)throw new Exception("Копия не подготовлена");try(OutputStream o=getContentResolver().openOutputStream(intent.getData())){o.write(exportBytes);}exportBytes=null;notifyJs("Защищённая копия сохранена");}
   if(req==12||req==15){
    admin();JSONObject backup=readBackup(intent.getData());int imageCount=validateBackup(backup);JSONArray imported=backup.getJSONArray("projects");
    if(req==15){new AlertDialog.Builder(this).setTitle("Копия прошла проверку").setMessage("Объектов: "+imported.length()+". Фотографий: "+imageCount+". Пароль подходит, структура копии читается. Данные телефона не изменены.").setPositiveButton("Закрыть",null).show();return;}
    new AlertDialog.Builder(this).setTitle("Восстановить объекты?").setMessage("Объекты на телефоне будут заменены данными копии. Учётные записи останутся прежними.").setNegativeButton("Отмена",null).setPositiveButton("Восстановить",(d,w)->{
     JSONObject old=db;try{admin();JSONObject next=new JSONObject(db.toString());JSONArray fresh=new JSONArray(imported.toString());for(int i=0;i<fresh.length();i++){JSONObject p=fresh.getJSONObject(i);for(String arr:new String[]{"photos","estimatePhotos"}){JSONArray rows=p.optJSONArray(arr);if(rows!=null)for(int j=0;j<rows.length();j++)rows.getJSONObject(j).put("id",UUID.randomUUID().toString());}}
      next.put("projects",fresh);db=next;migratePhotos(db,false);save();notifyJs("Объекты восстановлены");
     }catch(Exception e){db=old;notifyJs("Ошибка восстановления: "+e.getMessage());}
    }).show();
   }
   if(req==16){admin();byte[] bytes=readBytes(getContentResolver().openInputStream(intent.getData()));if(bytes.length>5000000)throw new Exception("Прайс слишком большой");JSONObject updated=new JSONObject(new String(bytes,StandardCharsets.UTF_8));storeCatalog(updated);notifyJs("Прайс обновлён: "+updated.getJSONArray("materials").length()+" SKU");}
   if(req==13||req==14||req==18){
    if(req==14)editor();JSONObject p=project(pendingProject);String collection=req==14?"estimatePhotos":"photos";JSONArray target=p.optJSONArray(collection);if(target==null){target=new JSONArray();p.put(collection,target);}if(req==14&&target.length()>=12)throw new Exception("Не более 12 фото в одной смете");
    android.graphics.BitmapFactory.Options opts=new android.graphics.BitmapFactory.Options();opts.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(intent.getData())){android.graphics.BitmapFactory.decodeStream(in,null,opts);}opts.inSampleSize=1;while(Math.max(opts.outWidth,opts.outHeight)/opts.inSampleSize>(req==14?1200:1600))opts.inSampleSize*=2;opts.inJustDecodeBounds=false;
    android.graphics.Bitmap bitmap;try(InputStream in=getContentResolver().openInputStream(intent.getData())){bitmap=android.graphics.BitmapFactory.decodeStream(in,null,opts);}if(bitmap==null)throw new Exception("Не удалось открыть фото");ByteArrayOutputStream bytes=new ByteArrayOutputStream();bitmap.compress(android.graphics.Bitmap.CompressFormat.JPEG,req==14?72:80,bytes);bitmap.recycle();if(bytes.size()>1500000)throw new Exception("Фото слишком большое: выберите изображение меньшего размера");
    String id=UUID.randomUUID().toString();photos().put(id,bytes.toByteArray());JSONObject record=new JSONObject().put("id",id).put("date",new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.ROOT).format(new Date()));if(req==18)record.put("purchaseRef",pendingReceiptRef).put("documentType",pendingReceiptType);target.put(record);save();notifyJs(req==18?"Документ закупки добавлен":req==14?"Фото добавлено в смету":"Фото добавлено");
   }
  }catch(Exception e){notifyJs("Ошибка: "+e.getMessage());}
  finally{if((req==12||req==15)&&pendingRestorePassword!=null){Arrays.fill(pendingRestorePassword,'\0');pendingRestorePassword=null;}if(req==11)exportBytes=null;}
 }
 @Override public void onBackPressed(){web.evaluateJavascript("back()",null);}
 @Override protected void onDestroy(){closeCloud();super.onDestroy();}
}
