package ru.arhilab.estimate;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.print.*;import android.security.keystore.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;import javax.crypto.*;import javax.crypto.spec.*;
public class MainActivity extends Activity {
 WebView web,printWeb; JSONObject db,catalog; String userId=null; byte[] exportBytes=null; char[] pendingRestorePassword=null,cloudPassword=null; CloudSync cloudClient=null; PhotoStore images=null; int failures=0,skippedBackupPhotos=0;long blockedUntil=0; String pendingProject="",pendingReceiptRef="",pendingReceiptType="",startupWarning="";
 final Bridge nativeBridge=new Bridge(); volatile boolean f1WorkerRunning=false;
 volatile boolean importCancelled=false,importRunning=false;ImportEngine importEngine;
 ImportEngine imports()throws Exception{if(importEngine==null)importEngine=new ImportEngine(this,key());return importEngine;}
 void importNotify(){runOnUiThread(()->web.evaluateJavascript("if(window.importNativeUpdate)importNativeUpdate()",null));}
 String read(InputStream in)throws Exception {ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buf=new byte[8192];int n;while((n=in.read(buf))!=-1)b.write(buf,0,n);in.close();return b.toString("UTF-8");}
 byte[] readBytes(InputStream in)throws Exception {try(InputStream src=in;ByteArrayOutputStream b=new ByteArrayOutputStream()){byte[] buf=new byte[8192];int n;while((n=src.read(buf))!=-1)b.write(buf,0,n);return b.toByteArray();}}
 SecretKey key()throws Exception {KeyStore k=KeyStore.getInstance("AndroidKeyStore");k.load(null);if(!k.containsAlias("arhilab-data")){KeyGenerator g=KeyGenerator.getInstance("AES","AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder("arhilab-data",KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes("GCM").setEncryptionPaddings("NoPadding").build());g.generateKey();}return (SecretKey)k.getKey("arhilab-data",null);}
 String tokenHash(byte[] token)throws Exception{return Base64.getEncoder().encodeToString(MessageDigest.getInstance("SHA-256").digest(token));}
 void startSession()throws Exception{byte[] token=new byte[32];new SecureRandom().nextBytes(token);user().put("sessionHash",tokenHash(token));saveRaw();Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key());File tmp=new File(getFilesDir(),"session.tmp"),target=new File(getFilesDir(),"session.enc");try(FileOutputStream o=new FileOutputStream(tmp)){o.write(c.getIV());o.write(c.doFinal(new JSONObject().put("user",userId).put("token",Base64.getEncoder().encodeToString(token)).toString().getBytes(StandardCharsets.UTF_8)));o.getFD().sync();}if(!tmp.renameTo(target))throw new IOException("Не удалось сохранить сессию");Arrays.fill(token,(byte)0);}
 void loadSession(){File f=new File(getFilesDir(),"session.enc");if(!f.exists())return;try{byte[] all=java.nio.file.Files.readAllBytes(f.toPath());if(all.length<29)throw new IOException("Сессия повреждена");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Arrays.copyOfRange(all,0,12)));JSONObject s=new JSONObject(new String(c.doFinal(Arrays.copyOfRange(all,12,all.length)),StandardCharsets.UTF_8));JSONObject u=find(db.getJSONArray("users"),s.getString("user"));byte[] token=Base64.getDecoder().decode(s.getString("token"));if(token.length!=32||!MessageDigest.isEqual(tokenHash(token).getBytes(StandardCharsets.UTF_8),u.optString("sessionHash").getBytes(StandardCharsets.UTF_8)))throw new IOException("Сессия отозвана");userId=u.getString("id");Arrays.fill(token,(byte)0);}catch(Exception e){userId=null;f.delete();}}
 void endSession()throws Exception{user().remove("sessionHash");saveRaw();new File(getFilesDir(),"session.enc").delete();userId=null;}
 void save()throws Exception {JSONArray projects=db.getJSONArray("projects");for(int i=0;i<projects.length();i++){JSONObject p=projects.getJSONObject(i);LocalEstimates.ensure(p);F6Procurement.ensure(p);F7Documents.list(p);if(!p.has("expenses"))p.put("expenses",new JSONArray());}F1SyncLedger.capture(db);JSONObject sync=db.optJSONObject("cloud");if(sync!=null)sync.put("dirty",true);saveRaw();}
 void saveRaw()throws Exception{Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key());byte[] enc=c.doFinal(db.toString().getBytes(StandardCharsets.UTF_8));File f=new File(getFilesDir(),"data.enc"),tmp=new File(getFilesDir(),"data.tmp");try(FileOutputStream o=new FileOutputStream(tmp)){o.write(c.getIV());o.write(enc);o.getFD().sync();}if(f.exists()){File backup=new File(getFilesDir(),"data-previous.enc");java.nio.file.Files.copy(f.toPath(),backup.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);}if(!tmp.renameTo(f))throw new IOException("Не удалось сохранить данные");}
 void load()throws Exception{catalog=new JSONObject(read(getAssets().open("catalog.json")));File update=new File(getFilesDir(),"catalog-update.json");if(update.exists()){try{JSONObject latest=new JSONObject(new String(java.nio.file.Files.readAllBytes(update.toPath()),StandardCharsets.UTF_8));validateCatalog(latest);latest=CatalogPriceUpdate.merge(catalog,latest);validateCatalog(latest);catalog=latest;}catch(Exception e){startupWarning="Обновлённый прайс не открывается; загружен встроенный каталог: "+e.getMessage();}}File f=new File(getFilesDir(),"data.enc");if(!f.exists()){db=new JSONObject().put("schemaVersion",DataMigration.CURRENT).put("users",new JSONArray()).put("projects",new JSONArray());return;}byte[] all=java.nio.file.Files.readAllBytes(f.toPath());if(all.length<29)throw new IOException("Файл базы повреждён");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Arrays.copyOfRange(all,0,12)));JSONObject original=new JSONObject(new String(c.doFinal(Arrays.copyOfRange(all,12,all.length)),StandardCharsets.UTF_8));db=original;int oldVersion=original.optInt("schemaVersion",1);JSONObject updated=DataMigration.migrate(original);MigrationReport report=migratePhotos(updated,true);if(report.failed>0)startupWarning="Не удалось перенести "+report.failed+" фото. Объекты доступны; исходные данные фото сохранены. Первое проблемное фото: "+report.firstFailure+". Сделайте резервную копию в настройках.";if(report.migrated>0||oldVersion<DataMigration.CURRENT){File migrationBackup=new File(getFilesDir(),"data-pre-migration.enc");java.nio.file.Files.copy(f.toPath(),migrationBackup.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);db=updated;try{F1SyncLedger.capture(db);saveRaw();migrationLog("Успех: схема "+oldVersion+" → "+DataMigration.CURRENT+", фото "+report.migrated);}catch(Exception e){db=original;java.nio.file.Files.copy(migrationBackup.toPath(),f.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);migrationLog("Откат схемы "+oldVersion+": "+e.getClass().getSimpleName());startupWarning="Миграция не сохранена, исходная база восстановлена: "+e.getMessage();}}loadSession();}
 void migrationLog(String message){try{java.nio.file.Files.write(new File(getFilesDir(),"migration.log").toPath(),(new Date()+" · "+message+"\n").getBytes(StandardCharsets.UTF_8),java.nio.file.StandardOpenOption.CREATE,java.nio.file.StandardOpenOption.APPEND);}catch(Exception ignored){}}
 PhotoStore photos()throws Exception{if(images==null)images=new PhotoStore(new File(getFilesDir(),"images"),key());return images;}
 byte[] photoBytes(String data)throws Exception{String prefix="data:image/jpeg;base64,";if(!data.startsWith(prefix))throw new IOException("Некорректный формат фото");byte[] bytes=Base64.getDecoder().decode(data.substring(prefix.length()));if(bytes.length<4||(bytes[0]&255)!=255||(bytes[1]&255)!=216||(bytes[bytes.length-2]&255)!=255||(bytes[bytes.length-1]&255)!=217)throw new IOException("Повреждённый JPEG");return bytes;}
 static class MigrationReport{int migrated,failed;String firstFailure="";}
 MigrationReport migratePhotos(JSONObject database,boolean keepFailures)throws Exception{MigrationReport result=new MigrationReport();JSONArray projects=database.getJSONArray("projects");for(int i=0;i<projects.length();i++){JSONObject p=projects.getJSONObject(i);for(String arr:new String[]{"photos","estimatePhotos"}){JSONArray list=p.optJSONArray(arr);if(list==null)continue;for(int j=0;j<list.length();j++){try{JSONObject row=list.getJSONObject(j);if(!row.has("data"))continue;byte[] jpeg=photoBytes(row.getString("data"));String id=row.optString("id");if(!id.matches("[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}"))id=UUID.randomUUID().toString();photos().put(id,jpeg);row.put("id",id);row.remove("data");result.migrated++;}catch(Exception e){if(!keepFailures)throw e;result.failed++;if(result.firstFailure.isEmpty())result.firstFailure=p.optString("name","Объект")+", "+(arr.equals("photos")?"фото объекта":"фото сметы")+" №"+(j+1)+" ("+e.getMessage()+")";}}}}return result;}
 JSONArray photoPayload(JSONObject p,String arr)throws Exception{JSONArray source=p.optJSONArray(arr),out=new JSONArray();if(source==null)return out;for(int i=0;i<source.length();i++){try{JSONObject row=new JSONObject(source.getJSONObject(i).toString());if(!row.has("data"))row.put("data","data:image/jpeg;base64,"+Base64.getEncoder().encodeToString(photos().get(row.getString("id"))));photoBytes(row.getString("data"));out.put(row);}catch(Exception ignored){/* Keep the record in db; skip only its unavailable image in the view/export. */}}return out;}
 JSONObject backupContent()throws Exception{JSONObject out=new JSONObject().put("format","Arhilab-1").put("team",state().getJSONArray("users"));JSONArray projects=new JSONArray();JSONArray source=db.getJSONArray("projects");skippedBackupPhotos=0;for(int i=0;i<source.length();i++){JSONObject p=new JSONObject(source.getJSONObject(i).toString());for(String arr:new String[]{"photos","estimatePhotos"})if(p.has(arr)){JSONArray original=p.getJSONArray(arr),available=photoPayload(p,arr);skippedBackupPhotos+=original.length()-available.length();p.put(arr,available);}projects.put(p);}return out.put("projects",projects).put("catalog",catalog);}
 JSONObject fullBackupContent()throws Exception{JSONObject out=backupContent();if(skippedBackupPhotos>0)throw new IOException("Недоступно фото: "+skippedBackupPhotos+". Полная копия не создана.");JSONArray users=new JSONArray();for(int i=0;i<db.getJSONArray("users").length();i++){JSONObject u=new JSONObject(db.getJSONArray("users").getJSONObject(i).toString());u.remove("sessionHash");users.put(u);}out.put("format","Arhilab-2").put("schemaVersion",DataMigration.CURRENT).put("users",users);JSONObject settings=db.optJSONObject("settings");if(settings!=null)out.put("settings",new JSONObject(settings.toString()));return out;}
 String diagnostics()throws Exception{JSONObject report=DataIntegrity.check(db,catalog);JSONArray issues=report.getJSONArray("issues"),ps=db.getJSONArray("projects");for(int i=0;i<ps.length();i++){JSONObject p=ps.getJSONObject(i);for(String arr:new String[]{"photos","estimatePhotos"}){JSONArray rows=p.optJSONArray(arr);if(rows!=null)for(int j=0;j<rows.length();j++){JSONObject row=rows.getJSONObject(j);if(!row.has("data")&&row.has("id")&&!photos().exists(row.optString("id")))issues.put("Фото объекта "+p.optString("name")+": файл не найден, строка "+(j+1));}}}return report.toString();}
 void recordError(String action,Exception e){try{File file=new File(getFilesDir(),"errors.log");String msg=new Date()+" | 0.6.2 | "+action.replaceAll("[^a-zA-Z]","")+" | "+e.getClass().getSimpleName()+" | "+android.util.Log.getStackTraceString(e).replaceAll("(?i)(password|token|secret)[^\\n]*","[скрыто]")+"\n";java.nio.file.Files.write(file.toPath(),msg.getBytes(StandardCharsets.UTF_8),java.nio.file.StandardOpenOption.CREATE,java.nio.file.StandardOpenOption.APPEND);if(file.length()>500000){byte[] recent=java.nio.file.Files.readAllBytes(file.toPath());java.nio.file.Files.write(file.toPath(),Arrays.copyOfRange(recent,recent.length-250000,recent.length));}}catch(Exception ignored){}}
 public void onCreate(Bundle b){super.onCreate(b);try{load();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Ошибка открытия базы").setMessage("Данные не перезаписаны. "+e.getMessage()).setPositiveButton("Закрыть",(d,w)->finish()).show();return;}web=new WebView(this);web.setBackgroundColor(0xfff2f3ef);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setDomStorageEnabled(false);web.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);web.clearCache(true);web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}public void onPageFinished(WebView v,String url){if(!startupWarning.isEmpty()){String message=startupWarning;startupWarning="";new AlertDialog.Builder(MainActivity.this).setTitle("Проверка фотографий").setMessage(message).setPositiveButton("Понятно",null).show();}}});web.setWebChromeClient(new WebChromeClient());web.addJavascriptInterface(nativeBridge,"Native");setContentView(web);web.setOnApplyWindowInsetsListener((v,in)->{v.setPadding(in.getSystemWindowInsetLeft(),in.getSystemWindowInsetTop(),in.getSystemWindowInsetRight(),in.getSystemWindowInsetBottom());return in.consumeSystemWindowInsets();});web.loadUrl("file:///android_asset/index.html");}
 JSONObject find(JSONArray a,String id)throws Exception{for(int i=0;i<a.length();i++)if(a.getJSONObject(i).optString("id").equals(id))return a.getJSONObject(i);throw new Exception("Запись не найдена");}
 JSONObject user()throws Exception{if(userId==null)throw new Exception("Войдите в приложение");return find(db.getJSONArray("users"),userId);}
 String role()throws Exception{return user().getString("role");}
 void admin()throws Exception{if(!role().equals("admin"))throw new Exception("Доступно администратору");}
 void editor()throws Exception{if(role().equals("worker"))throw new Exception("Недостаточно прав");}
 String hash(String pw,String salt)throws Exception{PBEKeySpec p=new PBEKeySpec(pw.toCharArray(),Base64.getDecoder().decode(salt),120000,256);return Base64.getEncoder().encodeToString(SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256").generateSecret(p).getEncoded());}
 void password(JSONObject u,String pw)throws Exception{if(pw.length()<8)throw new Exception("Пароль: минимум 8 символов");byte[] b=new byte[16];new SecureRandom().nextBytes(b);String salt=Base64.getEncoder().encodeToString(b);u.put("salt",salt).put("hash",hash(pw,salt));}
 JSONObject safeUser(JSONObject u)throws Exception{return new JSONObject().put("id",u.getString("id")).put("name",u.getString("name")).put("login",u.getString("login")).put("role",u.getString("role"));}
 JSONObject project(String id)throws Exception{JSONObject p=find(db.getJSONArray("projects"),id);if(role().equals("worker")&&!p.optString("assigned").equals(userId))throw new Exception("Объект не назначен вам");return p;}
 void stripCosts(JSONObject p)throws Exception{for(String k:new String[]{"deliveryCost","overhead","otherCost","purchases","expenses"})p.remove(k);for(String arr:new String[]{"lines","materials"}){JSONArray a=p.optJSONArray(arr);if(a!=null)for(int i=0;i<a.length();i++){a.getJSONObject(i).remove("cost");a.getJSONObject(i).remove("materialCost");}}JSONArray visible=new JSONArray();JSONArray payments=p.optJSONArray("payments");if(payments!=null)for(int i=0;i<payments.length();i++)if(payments.getJSONObject(i).optString("kind").equals("income"))visible.put(payments.getJSONObject(i));p.put("payments",visible);JSONArray estimates=p.optJSONArray("estimates");if(estimates!=null)for(int i=0;i<estimates.length();i++)stripCosts(estimates.getJSONObject(i));}
 JSONObject state()throws Exception{String r=role();JSONObject out=new JSONObject().put("user",safeUser(user()));JSONArray ps=new JSONArray();for(int i=0;i<db.getJSONArray("projects").length();i++){JSONObject p=new JSONObject(db.getJSONArray("projects").getJSONObject(i).toString());if(r.equals("worker")){if(!p.optString("assigned").equals(userId))continue;JSONObject q=new JSONObject();for(String k:new String[]{"id","name","address","status","assigned","tasks","notes","photos"})if(p.has(k))q.put(k,p.get(k));
JSONArray assignedRequests=new JSONArray(),requests=p.optJSONArray("procurementRequests");
if(requests!=null)for(int j=0;j<requests.length();j++){JSONObject request=requests.getJSONObject(j);if(userId.equals(request.optString("assigneeId")))assignedRequests.put(request);}
q.put("procurementRequests",assignedRequests);p=q;}else if(!r.equals("admin"))stripCosts(p);if(!r.equals("admin")){JSONArray source=p.optJSONArray("photos"),visible=new JSONArray();if(source!=null)for(int j=0;j<source.length();j++)if(!source.getJSONObject(j).has("purchaseRef"))visible.put(source.getJSONObject(j));p.put("photos",visible);}ps.put(p);}out.put("projects",ps);JSONArray us=new JSONArray();if(!r.equals("worker"))for(int i=0;i<db.getJSONArray("users").length();i++)us.put(safeUser(db.getJSONArray("users").getJSONObject(i)));out.put("users",us);JSONObject f1=db.optJSONObject("f1Sync");out.put("syncSummary",new JSONObject().put("state",f1==null?"offline":f1.optString("syncState","pending_changes")).put("pendingOperations",f1==null?0:f1.optJSONArray("operations").length()).put("connected",f1!=null&&f1.has("url")).put("paymentCurrencyRequired",f1!=null&&f1.optBoolean("paymentCurrencyRequired")).put("running",f1WorkerRunning).put("incompleteLegacy",F1SyncLedger.hasPrivateLegacy(db)).put("conflicts",f1==null?0:f1.optJSONArray("conflicts").length()).put("lastSuccessfulSync",f1==null?JSONObject.NULL:f1.opt("lastSuccessfulSync")));if(r.equals("admin")){JSONObject info=db.optJSONObject("cloud");out.put("cloud",new JSONObject().put("url",info==null?"":info.optString("url")).put("revision",info==null?-1:info.optInt("revision",-1)).put("dirty",info!=null&&info.optBoolean("dirty")).put("connected",cloudClient!=null));}return out;}
 JSONObject visibleCatalog(int percent)throws Exception{String r=role();if(r.equals("worker"))return new JSONObject().put("works",new JSONArray()).put("materials",new JSONArray());JSONObject c=new JSONObject(catalog.toString());for(int i=0;i<c.getJSONArray("works").length();i++){JSONObject w=c.getJSONArray("works").getJSONObject(i);JSONObject tiers=w.optJSONObject("tiers");if(tiers!=null)for(String tier:new String[]{"economy","standard","premium"}){JSONObject kit=tiers.getJSONObject(tier);kit.put("materialPrice",MaterialMarkup.price(kit.getDouble("materialCost"),percent));}}for(int i=0;i<c.getJSONArray("materials").length();i++){JSONObject m=c.getJSONArray("materials").getJSONObject(i);m.put("price",MaterialMarkup.price(m.getDouble("cost"),percent));}if(!r.equals("admin")){for(String arr:new String[]{"works","materials"})for(int i=0;i<c.getJSONArray(arr).length();i++){c.getJSONArray(arr).getJSONObject(i).remove("cost");JSONObject item=c.getJSONArray(arr).getJSONObject(i);item.remove("materialCost");JSONObject tiers=item.optJSONObject("tiers");if(tiers!=null)for(String tier:new String[]{"economy","standard","premium"})tiers.getJSONObject(tier).remove("materialCost");}}return c;}
 double num(JSONObject a,String k)throws Exception{double n=a.optDouble(k,0);if(!Double.isFinite(n)||n<0||n>1e12)throw new Exception("Некорректное число: "+k);return n;}
 double positiveQuantity(JSONObject a,String k)throws Exception{String raw=a.get(k).toString();if(!raw.matches("(?:0|[1-9][0-9]{0,11})(?:\\.[0-9]{1,4})?"))throw new Exception("Неверное количество: "+k);double value=Double.parseDouble(raw);if(value<=0)throw new Exception("Количество должно быть больше нуля");return value;}
 String required(JSONObject a,String k)throws Exception{String s=a.optString(k).trim();if(s.isEmpty()||s.length()>5000)throw new Exception("Заполните поле: "+k);return s;}
 void validateCatalog(JSONObject c)throws Exception{if(!"ArhilabCatalog-2".equals(c.optString("format")))throw new Exception("Формат прайса не поддерживается");JSONArray works=c.getJSONArray("works"),materials=c.getJSONArray("materials");if(works.length()<1||materials.length()<1||works.length()>10000||materials.length()>10000)throw new Exception("Каталог пуст или слишком велик");Set<String> ids=new HashSet<>(),keys=new HashSet<>();for(int i=0;i<materials.length();i++){JSONObject m=materials.getJSONObject(i);String id=m.getString("id"),name=m.getString("name");if(id.isEmpty()||name.isEmpty()||!ids.add(id))throw new Exception("Повтор или пустой SKU");double cost=m.getDouble("cost");if(!Double.isFinite(cost)||cost<0||cost>1e12)throw new Exception("Некорректная закупка SKU");}for(int i=0;i<works.length();i++){JSONObject w=works.getJSONObject(i);if(!keys.add(w.getString("key"))||w.getString("id").isEmpty())throw new Exception("Повтор работы");for(String tier:new String[]{"economy","standard","premium"}){JSONObject kit=w.getJSONObject("tiers").getJSONObject(tier);double cost=kit.getDouble("materialCost");if(!Double.isFinite(cost)||cost<0||cost>1e12)throw new Exception("Некорректная цена комплекта");JSONArray refs=kit.getJSONArray("materialIds");for(int j=0;j<refs.length();j++)if(!ids.contains(refs.getString(j)))throw new Exception("Материал комплекта не найден: "+refs.getString(j));if(refs.length()==0&&cost!=0)throw new Exception("Комплект без товаров содержит стоимость");}}}
 JSONObject matchingWork(JSONObject l)throws Exception{JSONArray works=catalog.getJSONArray("works");for(int i=0;i<works.length();i++){JSONObject w=works.getJSONObject(i);if(!l.optString("key").isEmpty()&&l.optString("key").equals(w.optString("key")))return w;if(l.optString("name").equals(w.optString("name"))&&l.optString("category").equals(w.optString("category")))return w;}throw new Exception("Работа отсутствует в каталоге");}
 void setTier(JSONObject l,JSONObject w,String tier,int markup)throws Exception{if(!Arrays.asList("economy","standard","premium").contains(tier))throw new Exception("Неверный класс материалов");JSONObject kit=w.getJSONObject("tiers").getJSONObject(tier);JSONArray ids=kit.getJSONArray("materialIds"),names=new JSONArray();for(int i=0;i<ids.length();i++)names.put(find(catalog.getJSONArray("materials"),ids.getString(i)).getString("name"));l.put("materialTier",tier).put("materials",names).put("materialNote",kit.optString("note")).put("materialCost",kit.getDouble("materialCost")).put("materialPrice",MaterialMarkup.price(kit.getDouble("materialCost"),markup)).put("autoMaterial",ids.length()>0);l.remove("tiers");l.remove("kitOverrides");}
 void refreshKitOverrides(JSONObject l,JSONObject w,int markup)throws Exception{JSONObject kit=w.getJSONObject("tiers").getJSONObject(l.optString("materialTier","standard")),overrides=l.optJSONObject("kitOverrides");JSONArray ids=kit.getJSONArray("materialIds"),names=new JSONArray();double cost=kit.getDouble("materialCost");for(int i=0;i<ids.length();i++){String base=ids.getString(i);JSONObject original=find(catalog.getJSONArray("materials"),base),override=overrides==null?null:overrides.optJSONObject(base);if(override==null){names.put(original.getString("name"));continue;}JSONObject replacement=find(catalog.getJSONArray("materials"),override.getString("sku"));double qty=override.getDouble("qty");cost+=(replacement.getDouble("cost")-original.getDouble("cost"))*qty;names.put(replacement.getString("name"));}if(cost<0)throw new Exception("Замена делает стоимость комплекта отрицательной");l.put("materials",names).put("materialCost",Math.round(cost*100)/100.0).put("materialPrice",MaterialMarkup.price(cost,markup));}
 void storeCatalog(JSONObject updated)throws Exception{validateCatalog(updated);File target=new File(getFilesDir(),"catalog-update.json"),tmp=new File(getFilesDir(),"catalog-update.tmp");try(FileOutputStream out=new FileOutputStream(tmp)){out.write(updated.toString().getBytes(StandardCharsets.UTF_8));out.getFD().sync();}if(target.exists())java.nio.file.Files.copy(target.toPath(),new File(getFilesDir(),"catalog-previous.json").toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);else java.nio.file.Files.write(new File(getFilesDir(),"catalog-previous.json").toPath(),catalog.toString().getBytes(StandardCharsets.UTF_8));if(!tmp.renameTo(target))throw new IOException("Не удалось сохранить прайс");catalog=updated;java.nio.file.Files.write(new File(getFilesDir(),"catalog-updated.txt").toPath(),new Date().toString().getBytes(StandardCharsets.UTF_8));JSONObject meta=db.optJSONObject("cloud");if(meta!=null){meta.put("dirty",true);saveRaw();}}
 void closeCloud(){cloudClient=null;if(cloudPassword!=null){Arrays.fill(cloudPassword,'\0');cloudPassword=null;}}
 JSONObject remoteData(CloudSync.Vault vault,char[] password)throws Exception{if(vault.ciphertext==null)throw new IOException("На сервере пока нет данных. Сначала отправьте данные с первого телефона.");byte[] decoded;try{decoded=BackupCrypto.decrypt(vault.ciphertext,password);}catch(javax.crypto.AEADBadTagException e){throw new IOException("Пароль не подходит к зашифрованной базе сервера");}JSONObject data=new JSONObject(new String(decoded,StandardCharsets.UTF_8));if(!data.optString("format").equals("Arhilab-1"))throw new IOException("Неизвестный формат базы на сервере");validateBackup(data);return data;}
 void applyRemote(JSONObject data,CloudSync.Vault vault,CloudSync connection,boolean newDevice,char[] password)throws Exception{JSONObject previous=db;String previousUser=userId;try{JSONObject next=newDevice?new JSONObject().put("users",new JSONArray()):new JSONObject(db.toString());if(newDevice){JSONObject admin=new JSONObject().put("id",UUID.randomUUID().toString()).put("name","Администратор").put("login","admin").put("role","admin");password(admin,new String(password));next.getJSONArray("users").put(admin);userId=admin.getString("id");}JSONArray projects=new JSONArray(data.getJSONArray("projects").toString());for(int i=0;i<projects.length();i++){JSONObject p=projects.getJSONObject(i);for(String arr:new String[]{"photos","estimatePhotos"}){JSONArray rows=p.optJSONArray(arr);if(rows!=null)for(int j=0;j<rows.length();j++)rows.getJSONObject(j).put("id",UUID.randomUUID().toString());}}JSONObject importedCatalog=data.optJSONObject("catalog");if(importedCatalog!=null)validateCatalog(importedCatalog);next.put("projects",projects).put("cloud",new JSONObject().put("url",connection.url).put("revision",vault.revision).put("dirty",false));next.put("schemaVersion",1);next=DataMigration.migrate(next);migratePhotos(next,false);if(importedCatalog!=null)storeCatalog(importedCatalog);db=next;saveRaw();}catch(Exception e){db=previous;userId=previousUser;throw e;}}
 void beginBackupPicker(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/octet-stream").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"Arhilab-protected-backup.arhilab");startActivityForResult(i,11);}
 void f1Status(String status,String category){synchronized(nativeBridge){try{JSONObject sync=F1SyncLedger.state(db);sync.put("syncState",status);if(category!=null)sync.put("lastErrorCategory",category);saveRaw();}catch(Exception e){recordError("f1Status",e);}}}
 void f1StartLogin(String url,String organization,String email,String password){if(f1WorkerRunning)return;f1WorkerRunning=true;new Thread(()->{
  try{
   JSONObject sync;String device;
   synchronized(nativeBridge){sync=F1SyncLedger.state(db);device=sync.optString("deviceId");if(device.isEmpty()){device=UUID.randomUUID().toString();sync.put("deviceId",device);saveRaw();}}
   F1SyncTransport transport=new F1SyncTransport(url);
   JSONObject response=transport.login(organization,email,password,device);
   if(!response.getJSONObject("user").getString("role").equals("admin"))throw new IllegalStateException("Для отправки изменений требуется серверный администратор");
   synchronized(nativeBridge){if(userId==null)return;sync=F1SyncLedger.state(db);sync.put("url",url).put("organizationId",organization)
     .put("accessToken",response.getString("accessToken")).put("refreshToken",response.getString("refreshToken"))
     .put("syncState","pending_changes");saveRaw();}
   f1RunSync(transport);
  }catch(Exception failure){f1Status(failure instanceof F1SyncTransport.Failure&&((F1SyncTransport.Failure)failure).status==401?"auth_required":"retry_wait",
    failure instanceof F1SyncTransport.Failure?"server_rejected":"network");}
  finally{f1WorkerRunning=false;}
 },"arhilab-f1-login").start();}
 void f1StartSync(){if(f1WorkerRunning)return;f1WorkerRunning=true;new Thread(()->{
  try{String address;synchronized(nativeBridge){address=F1SyncLedger.state(db).getString("url");}
   f1RunSync(new F1SyncTransport(address));
  }catch(Exception failure){f1Status(failure instanceof F1SyncTransport.Failure&&((F1SyncTransport.Failure)failure).status==401?"auth_required":"retry_wait",
    failure instanceof F1SyncTransport.Failure?"server_rejected":"network");}
  finally{f1WorkerRunning=false;}
 },"arhilab-f1-sync").start();}
 JSONObject f1Request(F1SyncTransport transport,String method,String path,JSONObject body)throws Exception{
  String access,refresh;synchronized(nativeBridge){JSONObject state=F1SyncLedger.state(db);access=state.optString("accessToken");refresh=state.optString("refreshToken");}
  if(access.isEmpty())throw new F1SyncTransport.Failure(401);
  try{return transport.request(method,path,body,access);}catch(F1SyncTransport.Failure failure){
   if(failure.status!=401||refresh.isEmpty())throw failure;
   JSONObject tokens;
   try{tokens=transport.refresh(refresh);}catch(Exception lost){
    // Rotation might have committed before the response was lost. Do not reuse the same refresh token.
    synchronized(nativeBridge){JSONObject state=F1SyncLedger.state(db);state.remove("refreshToken");state.remove("accessToken");state.put("syncState","auth_required");saveRaw();}
    throw new F1SyncTransport.Failure(401);
   }
   synchronized(nativeBridge){JSONObject state=F1SyncLedger.state(db);if(!state.optString("refreshToken").equals(refresh))throw new F1SyncTransport.Failure(401);
    state.put("accessToken",tokens.getString("accessToken")).put("refreshToken",tokens.getString("refreshToken"));saveRaw();access=state.getString("accessToken");}
   return transport.request(method,path,body,access);
  }
 }
 void f1RunSync(F1SyncTransport transport)throws Exception{
  synchronized(nativeBridge){if(userId==null)throw new IllegalStateException("Войдите локально");F1SyncLedger.state(db).put("syncState","syncing");saveRaw();}
  boolean bootstrap;synchronized(nativeBridge){JSONObject state=F1SyncLedger.state(db);
   bootstrap=db.getJSONArray("projects").length()==0&&state.getJSONArray("operations").length()==0&&state.optString("cursor","0").equals("0");}
  if(bootstrap){JSONObject snapshot=f1Request(transport,"GET","/sync/snapshot",null);
   synchronized(nativeBridge){JSONObject state=F1SyncLedger.state(db);
    if(db.getJSONArray("projects").length()==0&&state.getJSONArray("operations").length()==0){JSONObject next=new JSONObject(db.toString());
     JSONArray entities=snapshot.getJSONArray("entities");for(int i=0;i<entities.length();i++)F1SyncMerge.apply(next,entities.getJSONObject(i));
     F1SyncLedger.state(next).put("cursor",snapshot.getString("cursor"));JSONObject old=db;db=next;
     try{saveRaw();}catch(Exception e){db=old;throw e;}
    }
   }
  }
  while(true){JSONObject operation=null;
   synchronized(nativeBridge){JSONArray jobs=F1SyncLedger.state(db).getJSONArray("operations");
    for(int i=0;i<jobs.length();i++){JSONObject job=jobs.getJSONObject(i);if(!job.optString("state").equals("pending"))continue;
     boolean blocked=false;for(int j=0;j<i;j++){JSONObject earlier=jobs.getJSONObject(j);
      if(earlier.getString("entityId").equals(job.getString("entityId"))&&earlier.getString("entityType").equals(job.getString("entityType")))blocked=true;}
     if(!blocked){operation=new JSONObject(job.toString());break;}
    }
   }
   if(operation==null)break;
   String operationId=operation.getString("operationId");operation.remove("state");
   JSONObject result=f1Request(transport,"POST","/sync/push",new JSONObject().put("operations",new JSONArray().put(operation)));
   JSONArray results=result.getJSONArray("results");if(results.length()!=1)throw new IllegalStateException("Сервер не подтвердил операцию");
   synchronized(nativeBridge){JSONObject next=new JSONObject(db.toString());
    F1SyncLedger.acknowledge(next,results.getJSONObject(0));JSONObject old=db;db=next;
    try{saveRaw();}catch(Exception e){db=old;throw e;}
   }
  }
  while(true){String cursor;synchronized(nativeBridge){cursor=F1SyncLedger.state(db).optString("cursor","0");}
   JSONObject response=f1Request(transport,"GET","/sync/pull?cursor="+cursor,null);
   synchronized(nativeBridge){JSONObject next=new JSONObject(db.toString());JSONArray changes=response.getJSONArray("changes");
    for(int i=0;i<changes.length();i++)F1SyncMerge.apply(next,changes.getJSONObject(i));
    F1SyncLedger.state(next).put("cursor",response.getString("nextCursor"));JSONObject old=db;db=next;
    try{saveRaw();}catch(Exception e){db=old;throw e;}
   }
   if(!response.getBoolean("hasMore"))break;
  }
  synchronized(nativeBridge){JSONObject state=F1SyncLedger.state(db);JSONArray jobs=state.getJSONArray("operations");boolean conflicts=false;
   for(int i=0;i<jobs.length();i++)if(jobs.getJSONObject(i).optString("state").equals("conflict"))conflicts=true;
   state.put("syncState",conflicts?"conflict":jobs.length()>0||state.optBoolean("paymentCurrencyRequired")?"pending_changes":"idle")
    .put("lastSuccessfulSync",java.time.Instant.now().toString()).remove("lastErrorCategory");saveRaw();}
 }
 class Bridge {
 @JavascriptInterface public synchronized String call(String action,String raw){JSONObject before=null;try{JSONObject a=new JSONObject(raw);JSONObject result=new JSONObject();
 if(action.equals("session")){if(userId==null)return "{\"ok\":true,\"active\":false}";return new JSONObject().put("ok",true).put("active",true).put("state",state()).toString();}
 if(action.equals("status"))return new JSONObject().put("ok",true).put("setup",db.getJSONArray("users").length()==0).toString();
 if(action.equals("setup")){if(db.getJSONArray("users").length()!=0)throw new Exception("Администратор уже создан");JSONObject u=new JSONObject().put("id",UUID.randomUUID().toString()).put("name",required(a,"name")).put("login","admin").put("role","admin");password(u,required(a,"password"));db.getJSONArray("users").put(u);save();userId=u.getString("id");startSession();return new JSONObject().put("ok",true).put("state",state()).toString();}
 if(action.equals("cloudLogin")){if(db.getJSONArray("users").length()!=0)throw new Exception("На этом телефоне уже есть база. Войдите локально и подключите сервер в настройках.");char[] secret=required(a,"password").toCharArray();try{if(secret.length<12)throw new Exception("Пароль сервера: минимум 12 символов");CloudSync candidate=new CloudSync(required(a,"url"));candidate.login(required(a,"login"),secret);CloudSync.Vault vault=candidate.fetch();JSONObject contents=remoteData(vault,secret);applyRemote(contents,vault,candidate,true,secret);cloudClient=candidate;cloudPassword=secret;secret=null;startSession();return new JSONObject().put("ok",true).put("state",state()).toString();}finally{if(secret!=null)Arrays.fill(secret,'\0');}}
 if(action.equals("login")){if(System.currentTimeMillis()<blockedUntil)throw new Exception("Слишком много попыток. Повторите через минуту");JSONObject match=null;for(int i=0;i<db.getJSONArray("users").length();i++){JSONObject u=db.getJSONArray("users").getJSONObject(i);if(u.getString("login").equals(a.optString("login"))&&MessageDigest.isEqual(hash(a.optString("password"),u.getString("salt")).getBytes(StandardCharsets.UTF_8),u.getString("hash").getBytes(StandardCharsets.UTF_8)))match=u;}if(match==null){failures++;if(failures>=5){blockedUntil=System.currentTimeMillis()+60000;failures=0;}throw new Exception("Неверный логин или пароль");}userId=match.getString("id");startSession();failures=0;return new JSONObject().put("ok",true).put("state",state()).toString();}
 user();before=new JSONObject(db.toString());
 switch(action){
 case "importOriginal":{editor();JSONObject p=project(a.getString("project"));JSONArray docs=p.optJSONArray("sourceDocuments");if(docs==null)throw new Exception("Исходная смета недоступна");JSONObject d=find(docs,a.getString("id"));JSONObject page=d.getJSONArray("pages").getJSONObject(a.getInt("page"));result.put("image",imports().preview(page.getString("fileId"),page.optBoolean("pdf"),page.optInt("index"),page.optInt("rotation")));break;}
 case "importState":{editor();JSONObject session=db.optJSONObject("importSession");result.put("importSession",session==null?JSONObject.NULL:new JSONObject(session.toString()));break;}
 case "importStart":{editor();if(db.optJSONObject("importSession")!=null)throw new Exception("Сначала продолжите или удалите предыдущий импорт");db.put("importSession",new JSONObject().put("id",UUID.randomUUID().toString()).put("status","draft").put("createdAt",java.time.Instant.now().toString()).put("pages",new JSONArray()).put("rows",new JSONArray()));saveRaw();break;}
 case "importPick":{editor();JSONObject s=db.getJSONObject("importSession");if(s.optString("status").equals("imported"))throw new Exception("Импорт завершён");String source=required(a,"source");runOnUiThread(()->{Intent intent;
  if(source.equals("camera")){File dest=new File(getCacheDir(),"estimate-capture.jpg");dest.delete();Uri uri=Uri.parse("content://ru.arhilab.estimate.importcamera/capture");intent=new Intent(android.provider.MediaStore.ACTION_IMAGE_CAPTURE).putExtra(android.provider.MediaStore.EXTRA_OUTPUT,uri).setClipData(ClipData.newUri(getContentResolver(),"Скан",uri)).addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(intent,31);}
  else{intent=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(source.equals("pdf")?"application/pdf":"image/*");if(source.equals("photo"))intent.putExtra(Intent.EXTRA_ALLOW_MULTIPLE,true);startActivityForResult(intent,source.equals("pdf")?33:32);}});break;}
 case "importUpdate":{editor();JSONObject s=db.getJSONObject("importSession");if(importRunning)throw new Exception("Дождитесь завершения распознавания");JSONArray pages=a.optJSONArray("pages"),rows=a.optJSONArray("rows");if(pages!=null){JSONArray existing=s.getJSONArray("pages");if(pages.length()!=existing.length())throw new Exception("Неверное число страниц");HashSet<String> ids=new HashSet<>();for(int i=0;i<existing.length();i++)ids.add(existing.getJSONObject(i).getString("id"));for(int i=0;i<pages.length();i++){JSONObject p=pages.getJSONObject(i);if(!ids.remove(p.getString("id")))throw new Exception("Неизвестная страница");int rotation=p.optInt("rotation");if(rotation%90!=0)throw new Exception("Неверный угол поворота");}s.put("pages",pages);}
  if(rows!=null){if(rows.length()>5000)throw new Exception("Слишком много строк");s.put("rows",rows).put("status","review");}saveRaw();break;}
 case "importPage":{editor();JSONObject s=db.getJSONObject("importSession");int index=a.getInt("index");JSONObject p=s.getJSONArray("pages").getJSONObject(index);result.put("image",imports().preview(p.getString("fileId"),p.optBoolean("pdf"),p.optInt("index"),p.optInt("rotation")));break;}
 case "importRecognize":{editor();if(importRunning)throw new Exception("Распознавание уже выполняется");JSONObject s=db.getJSONObject("importSession");JSONArray pages=s.getJSONArray("pages");if(pages.length()==0)throw new Exception("Добавьте хотя бы одну страницу");importCancelled=false;importRunning=true;s.put("status","recognizing").put("progress",0);saveRaw();String sessionId=s.getString("id");new Thread(()->{try{JSONArray text=imports().recognize(pages,new ImportEngine.Progress(){public boolean cancelled(){return importCancelled;}public void page(int current,int total)throws Exception{synchronized(nativeBridge){JSONObject currentSession=db.optJSONObject("importSession");if(currentSession==null||!sessionId.equals(currentSession.optString("id")))throw new IOException("Импорт удалён");currentSession.put("progress",current).put("total",total);saveRaw();}importNotify();}});synchronized(nativeBridge){JSONObject current=db.optJSONObject("importSession");if(current!=null&&sessionId.equals(current.optString("id"))){current.put("recognizedPages",text).put("status","review").remove("error");saveRaw();}}}catch(Exception e){synchronized(nativeBridge){try{JSONObject current=db.optJSONObject("importSession");if(current!=null&&sessionId.equals(current.optString("id"))){current.put("status","draft").put("error",e.getMessage());saveRaw();}}catch(Exception ignored){}}}finally{importRunning=false;importNotify();}},"estimate-import-ocr").start();break;}
 case "importCancel":{editor();importCancelled=true;break;}
 case "importDelete":{editor();if(importRunning)throw new Exception("Сначала отмените распознавание");JSONObject s=db.optJSONObject("importSession");if(s!=null){JSONArray pages=s.optJSONArray("pages");if(pages!=null)for(int i=0;i<pages.length();i++)imports().file(pages.getJSONObject(i).getString("fileId")).delete();}db.remove("importSession");saveRaw();break;}
 case "importFinish":{editor();if(importRunning)throw new Exception("Распознавание не завершено");JSONObject session=db.getJSONObject("importSession");JSONArray rows=session.getJSONArray("rows");if(rows.length()==0)throw new Exception("Нет строк для создания сметы");String name=required(a,"name"),estimateName=required(a,"estimateName");if(name.length()>250||estimateName.length()>250)throw new Exception("Слишком длинное название");String projectId=UUID.randomUUID().toString(),estimateId=UUID.randomUUID().toString();JSONObject p=new JSONObject().put("id",projectId).put("name",name).put("address",a.optString("address")).put("client","").put("status","Новый").put("assigned","").put("materialMarkup",8).put("workMarkupPercent","0");for(String k:new String[]{"lines","materials","tasks","payments","expenses","notes","photos","estimatePhotos"})p.put(k,new JSONArray());p.put("delivery",0).put("discount",0);if(role().equals("admin"))for(String k:new String[]{"deliveryCost","overhead","otherCost"})p.put(k,0);
 JSONObject e=new JSONObject().put("id",estimateId).put("projectId",projectId).put("name",estimateName).put("legacy",false).put("serverRevision",0).put("lifecycleStatus","active").put("lines",new JSONArray()).put("materials",new JSONArray()).put("delivery",0).put("discount",0).put("workMarkupPercent","0").put("materialMarkup",8);
 int warnings=0,corrections=0;for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);if(row.optBoolean("deleted"))continue;String title=row.optString("name").trim();if(title.isEmpty())throw new Exception("У строки "+(i+1)+" нет названия");double qty=row.optDouble("qty",Double.NaN),price=row.optDouble("price",Double.NaN);if(!Double.isFinite(qty)||qty<=0||!Double.isFinite(price)||price<0)throw new Exception("Проверьте количество и цену строки "+(i+1));if(row.optBoolean("needsReview")&&!row.optBoolean("reviewed"))warnings++;if(row.optBoolean("reviewed"))corrections++;String id=UUID.randomUUID().toString();e.getJSONArray("lines").put(new JSONObject().put("id",id).put("syncId",id).put("name",title).put("unit",row.optString("unit","шт.")).put("qty",qty).put("coef",1).put("price",price).put("autoMaterial",false).put("manual",true).put("section",row.optString("section","Импортированные работы")).put("importedAmount",row.opt("amount")).put("sourcePage",row.optInt("page",1)).put("catalogMatchId",row.optString("catalogId")));}
 if(warnings>0&&!a.optBoolean("acceptWarnings"))throw new Exception("Остались строки для проверки: "+warnings);if(e.getJSONArray("lines").length()==0)throw new Exception("Все строки удалены");JSONArray pages=session.getJSONArray("pages");JSONArray originals=new JSONArray();HashSet<String> seen=new HashSet<>();for(int i=0;i<pages.length();i++){JSONObject item=pages.getJSONObject(i),copy=new JSONObject(item.toString());copy.remove("index");if(seen.add(copy.getString("fileId")))originals.put(copy);}JSONObject doc=new JSONObject().put("id",UUID.randomUUID().toString()).put("type","SOURCE_ESTIMATE").put("name","Исходная смета").put("createdAt",java.time.Instant.now().toString()).put("pageCount",pages.length()).put("files",originals).put("estimateId",estimateId);
 e.put("importMetadata",new JSONObject().put("sourceType",session.optString("sourceType","photo")).put("importedAt",java.time.Instant.now().toString()).put("originalDocumentId",doc.getString("id")).put("recognizedRows",rows.length()).put("manualCorrections",corrections));doc.put("pages",new JSONArray(pages.toString()));p.put("sourceDocuments",new JSONArray().put(doc));p.put("estimates",new JSONArray().put(e));db.getJSONArray("projects").put(p);db.remove("importSession");save();result.put("projectId",projectId).put("estimateId",estimateId);break;}
 case "f7List":{admin();JSONObject p=project(a.getString("project"));String estimateId=a.getString("estimateId");F7Documents.estimate(p,estimateId);JSONArray visible=new JSONArray(),all=F7Documents.list(p);for(int i=0;i<all.length();i++){JSONObject d=all.getJSONObject(i);if(estimateId.equals(d.optString("estimateId")))visible.put(new JSONObject(d.toString()));}result.put("documents",visible);break;}
 case "f7Create":{admin();JSONObject p=project(a.getString("project"));JSONObject d=F7Documents.create(p,a.getString("estimateId"),a.getString("type"),a.getJSONObject("settings"),a.getString("requestId"),userId,db.getJSONArray("projects"));save();result.put("document",new JSONObject(d.toString()));break;}
 case "f7Finalize":{admin();JSONObject p=project(a.getString("project"));JSONObject d=F7Documents.finalizeDocument(p,a.getString("id"));save();result.put("document",new JSONObject(d.toString()));break;}
 case "f7Get":{admin();JSONObject p=project(a.getString("project"));JSONObject d=F7Documents.document(p,a.getString("id"));result.put("document",new JSONObject(d.toString()));break;}
 case "f7Pdf":{admin();JSONObject p=project(a.getString("project"));JSONObject d=F7Documents.document(p,a.getString("id"));if(!d.optString("status").equals("final"))throw new Exception("Сначала утвердите документ");
  File pdf=F7Pdf.render(getCacheDir(),d);android.net.Uri uri=android.net.Uri.parse("content://ru.arhilab.estimate.documents/"+d.getString("id")+".pdf");
  boolean share=a.optBoolean("share");runOnUiThread(()->{Intent intent=new Intent(share?Intent.ACTION_SEND:Intent.ACTION_VIEW);
    if(share){intent.setType("application/pdf");intent.putExtra(Intent.EXTRA_STREAM,uri);intent.setClipData(ClipData.newUri(getContentResolver(),"PDF",uri));}
    else intent.setDataAndType(uri,"application/pdf");
    intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(intent,share?"Поделиться PDF":"Открыть PDF"));});
  result.put("bytes",pdf.length());break;}
 case "f1SyncConnect":{admin();String address=required(a,"url"),organization=required(a,"organizationId"),email=required(a,"email"),secret=required(a,"password");
  new F1SyncTransport(address);UUID.fromString(organization);JSONObject sync=F1SyncLedger.state(db);
  if(sync.has("organizationId")&&!sync.getString("organizationId").equals(organization))throw new Exception("Устройство связано с другой организацией");
  if(sync.has("url")&&!sync.getString("url").equals(address))throw new Exception("Смена сервера требует отдельной миграции");
  if(f1WorkerRunning)throw new Exception("Синхронизация уже выполняется");f1StartLogin(address,organization,email,secret);result.put("started",true);break;}
 case "f1SyncNow":{admin();if(f1WorkerRunning)throw new Exception("Синхронизация уже выполняется");if(!F1SyncLedger.state(db).has("url"))throw new Exception("Подключите сервер синхронизации");f1StartSync();result.put("started",true);break;}
 case "logout":endSession();closeCloud();return "{\"ok\":true}";
 case "state":break;
 case "cloudConnect":{admin();char[] secret=required(a,"password").toCharArray();try{if(secret.length<12)throw new Exception("Пароль сервера: минимум 12 символов");CloudSync candidate=new CloudSync(required(a,"url"));JSONObject old=db.optJSONObject("cloud");if(old!=null&&!old.optString("url").equals(candidate.url))throw new Exception("Устройство уже связано с другим сервером");candidate.login(required(a,"login"),secret);CloudSync.Vault vault=candidate.fetch();if(old==null){db.put("cloud",new JSONObject().put("url",candidate.url).put("revision",vault.ciphertext==null?0:-1).put("dirty",true));saveRaw();}closeCloud();cloudClient=candidate;cloudPassword=secret;secret=null;result.put("serverRevision",vault.revision);break;}finally{if(secret!=null)Arrays.fill(secret,'\0');}}
 case "cloudPush":{admin();if(cloudClient==null||cloudPassword==null)throw new Exception("Сначала подключитесь к серверу");JSONObject meta=db.getJSONObject("cloud");int revision=meta.optInt("revision",-1);if(revision<0)throw new Exception("На сервере уже есть база. Сначала получите её или используйте новый сервер.");JSONObject content=backupContent();if(skippedBackupPhotos>0)throw new Exception("Недоступно фото: "+skippedBackupPhotos+". Исправьте фото, прежде чем отправлять копию в общую базу.");byte[] encrypted=BackupCrypto.encrypt(content.toString().getBytes(StandardCharsets.UTF_8),cloudPassword);int updated=cloudClient.push(revision,encrypted);meta.put("revision",updated).put("dirty",false);saveRaw();result.put("serverRevision",updated);break;}
 case "cloudPull":{admin();if(cloudClient==null||cloudPassword==null)throw new Exception("Сначала подключитесь к серверу");CloudSync.Vault vault=cloudClient.fetch();JSONObject contents=remoteData(vault,cloudPassword);JSONObject meta=db.optJSONObject("cloud");if(db.getJSONArray("projects").length()>0&&!a.optBoolean("replace"))throw new Exception("Получение заменит локальные объекты. Сначала сохраните резервную копию и подтвердите замену.");if(meta!=null&&meta.optInt("revision",-1)>vault.revision)throw new Exception("Версия сервера старее локальной. Обратитесь к администратору сервера.");applyRemote(contents,vault,cloudClient,false,cloudPassword);result.put("serverRevision",vault.revision);break;}
 case "importCatalog":{admin();runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,16);});break;}
 case "catalogInfo":{editor();File updated=new File(getFilesDir(),"catalog-updated.txt");result.put("skuCount",catalog.getJSONArray("materials").length()).put("version",catalog.optString("sourceSha256",catalog.optString("version","Встроенный"))).put("updated",updated.exists()?new String(java.nio.file.Files.readAllBytes(updated.toPath()),StandardCharsets.UTF_8):"Встроенный каталог").put("source",catalog.optString("source","Встроенный прайс"));break;}
 case "catalog":result.put("catalog",visibleCatalog(a.optString("project").isEmpty()?8:project(a.getString("project")).optInt("materialMarkup",8)));break;
 case "photoData":{JSONObject p=project(a.getString("project"));String arr=a.getString("array");if(!arr.equals("photos")&&!arr.equals("estimatePhotos"))throw new Exception("Неверный раздел фото");if(arr.equals("estimatePhotos"))editor();JSONArray available=photoPayload(p,arr),all=p.optJSONArray(arr);if(!role().equals("admin")&&arr.equals("photos")){JSONArray visible=new JSONArray();for(int i=0;i<available.length();i++)if(!available.getJSONObject(i).has("purchaseRef"))visible.put(available.getJSONObject(i));available=visible;}result.put("photos",available).put("missingPhotos",all==null?0:all.length()-available.length());break;}
 case "password":if(!hash(a.optString("old"),user().getString("salt")).equals(user().getString("hash")))throw new Exception("Текущий пароль неверен");password(user(),required(a,"password"));startSession();break;
 case "user":{admin();String login=required(a,"login");for(int i=0;i<db.getJSONArray("users").length();i++)if(db.getJSONArray("users").getJSONObject(i).getString("login").equals(login))throw new Exception("Логин уже занят");String r=a.optString("role");if(!r.equals("manager")&&!r.equals("worker"))throw new Exception("Выберите роль");JSONObject u=new JSONObject().put("id",UUID.randomUUID().toString()).put("login",login).put("name",required(a,"name")).put("role",r);password(u,required(a,"password"));db.getJSONArray("users").put(u);save();break;}
 case "resetPassword":{admin();JSONObject target=find(db.getJSONArray("users"),a.getString("id"));password(target,required(a,"password"));target.remove("sessionHash");if(target.getString("id").equals(userId))endSession();else save();break;}
 case "project":{editor();JSONObject p;if(a.optString("id").isEmpty()){p=new JSONObject().put("id",UUID.randomUUID().toString()).put("materialMarkup",8).put("workMarkupPercent","0");for(String k:new String[]{"lines","materials","tasks","payments","expenses","notes","photos","estimatePhotos"})p.put(k,new JSONArray());db.getJSONArray("projects").put(p);}else p=project(a.getString("id"));p.put("name",required(a,"name")).put("address",a.optString("address")).put("client",a.optString("client")).put("status",a.optString("status","Новый")).put("assigned",a.optString("assigned"));for(String k:new String[]{"delivery","discount"})p.put(k,num(a,k));if(role().equals("admin"))for(String k:new String[]{"deliveryCost","overhead","otherCost"})p.put(k,num(a,k));save();result.put("projectId",p.getString("id"));break;}
 case "materialMarkup":{editor();JSONObject p=project(a.getString("project"));int percent=MaterialMarkup.validate(a.getInt("percent"));JSONArray ms=p.getJSONArray("materials");for(int i=0;i<ms.length();i++){JSONObject m=ms.getJSONObject(i);if(m.has("cost"))m.put("price",MaterialMarkup.price(m.getDouble("cost"),percent));}JSONArray lines=p.getJSONArray("lines");for(int i=0;i<lines.length();i++){JSONObject l=lines.getJSONObject(i);if(l.has("materialCost"))l.put("materialPrice",MaterialMarkup.price(l.getDouble("materialCost"),percent));}p.put("materialMarkup",percent);save();break;}
 case "workMarkup":{editor();JSONObject p=project(a.getString("project"));String input=a.getString("percent").trim();if(!input.matches("(?:0|[1-9][0-9]?|100)(?:\\.[0-9]{1,2})?"))throw new Exception("Наценка на работы: от 0 до 100%, максимум 2 знака после запятой");java.math.BigDecimal percent=new java.math.BigDecimal(input);if(percent.compareTo(new java.math.BigDecimal("100"))>0)throw new Exception("Наценка на работы не может превышать 100%");p.put("workMarkupPercent",percent.toPlainString());save();break;}
 case "estimateCreate":{editor();JSONObject p=project(a.getString("project"));String id=UUID.randomUUID().toString();JSONObject estimate=new JSONObject().put("id",id).put("projectId",p.getString("id")).put("name",required(a,"name")).put("legacy",false).put("serverRevision",0).put("lifecycleStatus","active").put("lines",new JSONArray()).put("materials",new JSONArray()).put("delivery",0).put("discount",0).put("workMarkupPercent","0").put("materialMarkup",8);p.getJSONArray("estimates").put(estimate);save();result.put("estimateId",id);break;}
 case "estimateLifecycleInfo":{editor();JSONObject p=project(a.getString("project")),e=find(p.getJSONArray("estimates"),a.getString("id"));result.put("status",EstimateLifecycle.status(e)).put("dependencies",EstimateLifecycle.dependencies(p,e));break;}
 case "estimateLifecycle":{editor();JSONObject p=project(a.getString("project")),e=find(p.getJSONArray("estimates"),a.getString("id"));String change=a.getString("change");if(change.equals("delete"))admin();EstimateLifecycle.transition(p,e,change,a.optBoolean("confirmed"),a.optBoolean("relatedAcknowledged"),a.optString("confirmationName"));save();result.put("status",EstimateLifecycle.status(e));break;}
 case "estimateUpdate":{editor();JSONObject p=project(a.getString("project")),estimate=find(p.getJSONArray("estimates"),a.getString("id"));if(!EstimateLifecycle.status(estimate).equals("active"))throw new Exception("Смета находится в архиве или удалена");if(estimate.optBoolean("legacy"))throw new Exception("Исходная смета редактируется во вкладке объекта");if(a.has("name"))estimate.put("name",required(a,"name"));if(a.has("delivery"))estimate.put("delivery",num(a,"delivery"));if(a.has("discount"))estimate.put("discount",num(a,"discount"));if(a.has("workMarkupPercent")){String value=a.getString("workMarkupPercent");if(!value.matches("(?:0|[1-9][0-9]?|100)(?:\\.[0-9]{1,2})?")||new java.math.BigDecimal(value).compareTo(new java.math.BigDecimal("100"))>0)throw new Exception("Некорректная наценка работ");estimate.put("workMarkupPercent",value);}save();break;}
 case "estimateItem":{editor();JSONObject p=project(a.getString("project")),estimate=find(p.getJSONArray("estimates"),a.getString("estimate"));if(!EstimateLifecycle.status(estimate).equals("active"))throw new Exception("Смета находится в архиве или удалена");if(estimate.optBoolean("legacy"))throw new Exception("Используйте исходную смету");String kind=a.getString("kind");if(!kind.equals("work")&&!kind.equals("material"))throw new Exception("Неверный тип строки");JSONObject line;String collection;
   if(kind.equals("work")){JSONObject w=find(catalog.getJSONArray("works"),a.getString("catalogId"));line=new JSONObject(w.toString()).put("coef",positiveQuantity(a,"coef")).put("price",num(a,"price")).put("autoMaterial",false);collection="lines";}
   else{JSONObject m=find(catalog.getJSONArray("materials"),a.getString("catalogId"));line=new JSONObject(m.toString()).put("price",num(a,"price"));collection="materials";}
   String id=UUID.randomUUID().toString();line.put("id",id).put("syncId",id).put("qty",positiveQuantity(a,"qty"));if(!role().equals("admin"))line.remove("cost");estimate.getJSONArray(collection).put(line);save();result.put("itemId",id);break;}
 case "estimateItemQuantity":{editor();JSONObject estimate=find(project(a.getString("project")).getJSONArray("estimates"),a.getString("estimate"));if(!EstimateLifecycle.status(estimate).equals("active"))throw new Exception("Смета находится в архиве или удалена");if(estimate.optBoolean("legacy"))throw new Exception("Используйте исходную смету");String kind=a.getString("kind");if(!kind.equals("lines")&&!kind.equals("materials"))throw new Exception("Неверный тип строки");JSONObject item=find(estimate.getJSONArray(kind),a.getString("id"));item.put("qty",positiveQuantity(a,"qty"));save();break;}
 case "estimateManualWork":{editor();JSONObject estimate=find(project(a.getString("project")).getJSONArray("estimates"),a.getString("estimate"));if(!EstimateLifecycle.status(estimate).equals("active"))throw new Exception("Смета находится в архиве или удалена");if(estimate.optBoolean("legacy"))throw new Exception("Используйте исходную смету");double price=num(a,"price");if(price<0)throw new Exception("Цена работы не может быть отрицательной");String id=UUID.randomUUID().toString();JSONObject line=new JSONObject().put("id",id).put("syncId",id).put("name",required(a,"name")).put("qty",positiveQuantity(a,"qty")).put("coef",positiveQuantity(a,"coef")).put("price",price).put("unit",a.optString("unit","шт.")).put("autoMaterial",false).put("manual",true);estimate.getJSONArray("lines").put(line);save();result.put("itemId",id);break;}
 case "estimateItemRemove":{editor();JSONObject estimate=find(project(a.getString("project")).getJSONArray("estimates"),a.getString("estimate"));if(!EstimateLifecycle.status(estimate).equals("active"))throw new Exception("Смета находится в архиве или удалена");if(estimate.optBoolean("legacy"))throw new Exception("Используйте исходную смету");String kind=a.getString("kind");if(!kind.equals("lines")&&!kind.equals("materials"))throw new Exception("Неверный тип строки");JSONArray items=estimate.getJSONArray(kind);boolean found=false;for(int i=0;i<items.length();i++)if(items.getJSONObject(i).getString("id").equals(a.getString("id"))){F4Execution.assertRemovable(estimate,items.getJSONObject(i).getString("syncId"));items.remove(i);found=true;break;}if(!found)throw new Exception("Строка не найдена");save();break;}
 case "estimateAddress":{editor();JSONObject p=project(a.getString("project"));String address=required(a,"address");p.put("address",address);save();break;}
 case "estimatePhoto":{editor();JSONObject p=project(a.getString("project"));if(p.optJSONArray("estimatePhotos")!=null&&p.getJSONArray("estimatePhotos").length()>=12)throw new Exception("Не более 12 фото в одной смете");pendingProject=p.getString("id");runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,14);});break;}
 case "removeEstimatePhoto":{editor();JSONObject p=project(a.getString("project"));JSONArray photos=p.optJSONArray("estimatePhotos");if(photos==null)throw new Exception("Фото не найдено");boolean removed=false;for(int i=0;i<photos.length();i++)if(photos.getJSONObject(i).optString("id").equals(a.optString("id"))){photos.remove(i);removed=true;break;}if(!removed)throw new Exception("Фото не найдено");save();try{photos().delete(a.getString("id"));}catch(Exception ignored){}break;}
 case "line":{editor();JSONObject p=project(a.getString("project")),w=find(catalog.getJSONArray("works"),a.getString("work"));double qty=num(a,"qty"),coef=num(a,"coef");if(qty==0||coef==0)throw new Exception("Объём и коэффициент должны быть больше нуля");JSONObject l=new JSONObject(w.toString()).put("id",UUID.randomUUID().toString()).put("qty",qty).put("coef",coef).put("price",num(a,"price"));CatalogPriceUpdate.requireQuotedPrice(w,l.getDouble("price"));setTier(l,w,a.optString("tier","standard"),p.optInt("materialMarkup",8));if(!a.optBoolean("autoMaterial"))l.put("autoMaterial",false);if(role().equals("admin"))l.put("cost",num(a,"cost"));if(a.optBoolean("extra"))l.put("extra",true).put("extraStatus","Создано").put("createdBy",user().getString("name")).put("createdAt",System.currentTimeMillis());p.getJSONArray("lines").put(l);save();break;}
 case "manualWork":{editor();JSONObject p=project(a.getString("project"));JSONObject l=new JSONObject().put("id",UUID.randomUUID().toString()).put("name",required(a,"name")).put("unit",required(a,"unit")).put("qty",positiveQuantity(a,"qty")).put("coef",positiveQuantity(a,"coef")).put("price",num(a,"price")).put("autoMaterial",false).put("manualWork",true);if(role().equals("admin"))l.put("cost",num(a,"cost"));p.getJSONArray("lines").put(l);save();break;}
 case "lineQuantity":{editor();JSONObject l=find(project(a.getString("project")).getJSONArray("lines"),a.getString("id"));l.put("qty",positiveQuantity(a,"qty"));save();break;}
 case "materialQuantity":{editor();JSONObject m=find(project(a.getString("project")).getJSONArray("materials"),a.getString("id"));m.put("qty",positiveQuantity(a,"qty"));save();break;}
 case "lineTier":{editor();JSONObject p=project(a.getString("project")),l=find(p.getJSONArray("lines"),a.getString("id")),w=matchingWork(l);setTier(l,w,a.getString("tier"),p.optInt("materialMarkup",8));save();break;}
 case "extraStatus":{editor();JSONObject l=find(project(a.getString("project")).getJSONArray("lines"),a.getString("id"));if(!l.optBoolean("extra"))throw new Exception("Это не дополнительная работа");String status=a.getString("status");if(!Arrays.asList("Создано","Отправлено на согласование","Согласовано","Выполняется","Выполнено","Оплачено","Отклонено").contains(status))throw new Exception("Неизвестный статус допработы");if(status.equals("Согласовано")&&!role().equals("admin"))throw new Exception("Согласование доступно администратору");l.put("extraStatus",status);if(status.equals("Согласовано"))l.put("approvedBy",user().getString("name"));save();break;}
 case "kitReplace":{editor();JSONObject p=project(a.getString("project")),l=find(p.getJSONArray("lines"),a.getString("id")),w=matchingWork(l);String base=a.getString("base"),tier=l.optString("materialTier","standard");JSONArray ids=w.getJSONObject("tiers").getJSONObject(tier).getJSONArray("materialIds");boolean found=false;for(int i=0;i<ids.length();i++)if(base.equals(ids.getString(i)))found=true;if(!found)throw new Exception("Материал отсутствует в комплекте");JSONObject overrides=l.optJSONObject("kitOverrides");if(overrides==null){overrides=new JSONObject();l.put("kitOverrides",overrides);}String sku=a.optString("sku",base);if(sku.equals(base))overrides.remove(base);else{find(catalog.getJSONArray("materials"),sku);double qty=num(a,"qty");if(qty<=0)throw new Exception("Укажите точный расход заменяемого материала на единицу работы");overrides.put(base,new JSONObject().put("sku",sku).put("qty",qty));}refreshKitOverrides(l,w,p.optInt("materialMarkup",8));save();break;}
 case "purchase":{admin();JSONObject p=project(a.getString("project"));String ref=required(a,"ref");if(ref.length()>150)throw new Exception("Некорректная позиция");boolean found=false;JSONArray lines=p.getJSONArray("lines");for(int i=0;i<lines.length();i++){JSONObject l=lines.getJSONObject(i);if(!ref.startsWith(l.optString("id")+":"))continue;String base=ref.substring(l.getString("id").length()+1);JSONArray ids=matchingWork(l).getJSONObject("tiers").getJSONObject(l.optString("materialTier","standard")).getJSONArray("materialIds");for(int j=0;j<ids.length();j++)if(base.equals(ids.getString(j)))found=true;}JSONArray manual=p.getJSONArray("materials");for(int i=0;i<manual.length();i++)if(ref.equals(manual.getJSONObject(i).optString("id")))found=true;if(!found)throw new Exception("Позиция сметы не найдена");double qty=num(a,"qty"),pack=num(a,"pack"),reserve=num(a,"reserve"),actual=num(a,"actual");if(pack<=0||reserve>100)throw new Exception("Проверьте упаковку и запас");String status=a.optString("status");if(!Arrays.asList("Нужно купить","Заказано","Оплачено","Доставлено","На объекте","Возврат").contains(status))throw new Exception("Неверный статус");JSONObject entries=p.optJSONObject("purchases");if(entries==null){entries=new JSONObject();p.put("purchases",entries);}entries.put(ref,new JSONObject().put("qty",qty).put("pack",pack).put("reserve",reserve).put("actual",actual).put("actualEntered",a.optBoolean("actualEntered")).put("status",status).put("updated",System.currentTimeMillis()));save();break;}
 case "material":{editor();JSONObject p=project(a.getString("project")),m=find(catalog.getJSONArray("materials"),a.getString("material"));double q=num(a,"qty");if(q==0)throw new Exception("Количество должно быть больше нуля");JSONObject l=new JSONObject(m.toString()).put("id",UUID.randomUUID().toString()).put("qty",q);double cost=role().equals("admin")?num(a,"cost"):m.getDouble("cost");l.put("cost",cost).put("price",MaterialMarkup.price(cost,p.optInt("materialMarkup",8)));p.getJSONArray("materials").put(l);save();break;}
 case "remove":{editor();String arr=a.getString("array");if(!Arrays.asList("lines","materials","payments","tasks").contains(arr))throw new Exception("Удаление запрещено");if(arr.equals("payments"))admin();JSONArray ar=project(a.getString("project")).getJSONArray(arr);for(int i=0;i<ar.length();i++)if(ar.getJSONObject(i).getString("id").equals(a.getString("id"))){if(arr.equals("lines")){JSONObject p=project(a.getString("project"));F4Execution.assertRemovable(find(p.getJSONArray("estimates"),p.getString("legacyEstimateId")),ar.getJSONObject(i).getString("syncId"));}ar.remove(i);break;}save();break;}
 case "payment":{admin();JSONObject p=project(a.getString("project"));double n=num(a,"amount");if(n==0)throw new Exception("Сумма должна быть больше нуля");p.getJSONArray("payments").put(new JSONObject().put("id",UUID.randomUUID().toString()).put("amount",n).put("kind",a.optString("kind").equals("expense")?"expense":"income").put("date",required(a,"date")).put("note",a.optString("note")).put("type",a.optString("type","Платёж за этап")).put("planDate",a.optString("planDate")).put("paid",num(a,"paid")));save();break;}
 case "paymentUpdate":{admin();JSONObject x=find(project(a.getString("project")).getJSONArray("payments"),a.getString("id"));double paid=num(a,"paid");if(paid>x.getDouble("amount"))throw new Exception("Оплата превышает сумму платежа");x.put("paid",paid).put("planDate",a.optString("planDate")).put("actualDate",a.optString("actualDate"));save();break;}
 case "f2EstimateCurrency":{admin();JSONObject estimate=find(project(a.getString("project")).getJSONArray("estimates"),a.getString("estimate"));
  String currency=F2Payments.currency(required(a,"currency"));
  JSONArray payments=project(a.getString("project")).getJSONArray("payments");
  for(int i=0;i<payments.length();i++){JSONObject payment=payments.getJSONObject(i);
   if(estimate.getString("id").equals(payment.optString("estimateId"))&&!currency.equals(payment.optString("currency")))
    throw new Exception("Сначала уточните валюту уже связанных платежей");}
  estimate.put("currency",currency);save();break;}
 case "f2PaymentCreate":{admin();JSONObject p=project(a.getString("project"));
  JSONObject estimate=find(p.getJSONArray("estimates"),a.getString("estimate"));
  String currency=F2Payments.currency(required(a,"currency"));
  if(!currency.equals(estimate.optString("currency")))throw new Exception("Валюта платежа должна совпадать с валютой сметы");
  String amount=F2Payments.amount(required(a,"amount"));String date=required(a,"date");java.time.LocalDate.parse(date);
  String note=a.optString("note","").trim();if(note.length()>1000)throw new Exception("Комментарий слишком длинный");
  String id=UUID.randomUUID().toString();p.getJSONArray("payments").put(new JSONObject().put("id",id).put("estimateId",estimate.getString("id"))
    .put("amount",amount).put("paid",amount).put("currency",currency).put("kind","income")
    .put("date",date).put("note",note).put("type","Платёж за этап"));save();result.put("paymentId",id);break;}
 case "f2PaymentEdit":{admin();JSONObject p=project(a.getString("project")),payment=find(p.getJSONArray("payments"),a.getString("id"));
  if(!"income".equals(payment.optString("kind"))||!payment.has("estimateId"))throw new Exception("Изменение этого платежа выполняется в исходном разделе объекта");
  F2Payments.edit(payment,required(a,"amount"),required(a,"date"),a.optString("note","").trim());save();break;}
 case "f2PaymentResolve":{admin();JSONObject p=project(a.getString("project")),payment=find(p.getJSONArray("payments"),a.getString("id"));
  String currency=F2Payments.currency(required(a,"currency"));String estimateId=a.optString("estimate","");
  if(!estimateId.isEmpty()){JSONObject estimate=find(p.getJSONArray("estimates"),estimateId);
   if(!"income".equals(payment.optString("kind"))||!currency.equals(estimate.optString("currency")))
    throw new Exception("Привязать можно только поступление в валюте сметы");payment.put("estimateId",estimateId);}
  payment.put("currency",currency);save();break;}
 case "f2PaymentDelete":{admin();JSONObject p=project(a.getString("project"));JSONArray payments=p.getJSONArray("payments");String id=a.getString("id");
  boolean removed=false;for(int i=0;i<payments.length();i++)if(id.equals(payments.getJSONObject(i).optString("id"))){payments.remove(i);removed=true;break;}
  if(!removed)throw new Exception("Платёж не найден");save();break;}
 case "f3ExpenseSave":{admin();JSONObject p=project(a.getString("project"));
  String estimateId=a.optString("estimate","");if(!estimateId.isEmpty())find(p.getJSONArray("estimates"),estimateId);
  String id=a.optString("id","");JSONArray expenses=p.optJSONArray("expenses");
  if(expenses==null){expenses=new JSONArray();p.put("expenses",expenses);}
  JSONObject expense=id.isEmpty()?new JSONObject().put("id",UUID.randomUUID().toString())
    .put("createdAt",java.time.Instant.now().toString()):find(expenses,id);
  expense.put("category",required(a,"category")).put("amount",required(a,"amount"))
    .put("currency",required(a,"currency")).put("date",required(a,"date"))
    .put("description",required(a,"description")).put("note",a.optString("note",""));
  String procurementId=a.optString("procurementRequestId",expense.optString("procurementRequestId",""));
  if(!procurementId.isEmpty()){
   F6Procurement.ensure(p);JSONObject linked=F6Procurement.find(p.getJSONArray("procurementRequests"),procurementId);
   if(!expense.optString("procurementRequestId",procurementId).equals(procurementId)||
      !linked.optString("estimateId","").equals(estimateId)||!expense.optString("category").equals("materials"))
      throw new Exception("Расход не соответствует заявке на материал");
   expense.put("procurementRequestId",procurementId);
  }
  if(estimateId.isEmpty())expense.remove("estimateId");else expense.put("estimateId",estimateId);
  F3Expenses.validate(expense);expense.put("updatedAt",java.time.Instant.now().toString());
  if(id.isEmpty())expenses.put(expense);save();result.put("expenseId",expense.getString("id"));break;}
 case "f3ExpenseDelete":{admin();JSONObject p=project(a.getString("project"));JSONArray expenses=p.getJSONArray("expenses");
  String id=required(a,"id");boolean removed=false;
  for(int i=0;i<expenses.length();i++)if(id.equals(expenses.getJSONObject(i).getString("id"))){expenses.remove(i);removed=true;break;}
  if(!removed)throw new Exception("Расход не найден");save();break;}
 case "f4StageSave":{admin();JSONObject p=project(required(a,"project"));LocalEstimates.ensure(p);JSONObject e=find(p.getJSONArray("estimates"),required(a,"estimate"));
  JSONObject stage=F4Execution.saveStage(e,a);save();result.put("stageId",stage.getString("id"));break;}
 case "f4StageDelete":{admin();JSONObject p=project(required(a,"project"));LocalEstimates.ensure(p);JSONObject e=find(p.getJSONArray("estimates"),required(a,"estimate"));
  F4Execution.deleteStage(e,required(a,"id"));save();break;}
 case "f4Assign":{admin();JSONObject p=project(required(a,"project"));LocalEstimates.ensure(p);JSONObject e=find(p.getJSONArray("estimates"),required(a,"estimate"));
  F4Execution.assign(e,required(a,"item"),a.optString("stage",""));save();break;}
 case "f4ProgressSave":{admin();JSONObject p=project(required(a,"project"));LocalEstimates.ensure(p);JSONObject e=find(p.getJSONArray("estimates"),required(a,"estimate"));
  JSONObject entry=F4Execution.saveEntry(e,a,user().getString("id"));save();result.put("entryId",entry.getString("id"));break;}
 case "f4ProgressDelete":{admin();JSONObject p=project(required(a,"project"));LocalEstimates.ensure(p);JSONObject e=find(p.getJSONArray("estimates"),required(a,"estimate"));
  F4Execution.deleteEntry(e,required(a,"id"));save();break;}
 case "f5TaskSave":{admin();JSONObject p=project(required(a,"project"));LocalEstimates.ensure(p);
  JSONObject task=F5Tasks.save(p,a);save();result.put("taskId",task.getString("id"));break;}
 case "f5TaskDelete":{admin();JSONObject p=project(required(a,"project"));JSONArray rows=p.getJSONArray("tasks");
  String id=required(a,"id");boolean found=false;for(int i=0;i<rows.length();i++)if(id.equals(rows.getJSONObject(i).getString("id"))){rows.remove(i);found=true;break;}
  if(!found)throw new Exception("Задача не найдена");save();break;}
 case "f6RequestSave":{admin();JSONObject p=project(required(a,"project"));LocalEstimates.ensure(p);
  JSONObject request=F6Procurement.saveRequest(p,a,catalog);save();result.put("requestId",request.getString("id"));break;}
 case "f6RequestDelete":{admin();JSONObject p=project(required(a,"project"));F6Procurement.delete(p,"request",required(a,"id"));save();break;}
 case "f6ReceiptSave":{admin();JSONObject p=project(required(a,"project"));
  JSONObject receipt=F6Procurement.saveReceipt(p,a);save();result.put("receiptId",receipt.getString("id"));break;}
 case "f6ReceiptDelete":{admin();JSONObject p=project(required(a,"project"));F6Procurement.delete(p,"receipt",required(a,"id"));save();break;}
 case "task":{editor();JSONObject p=project(a.getString("project"));p.getJSONArray("tasks").put(new JSONObject().put("id",UUID.randomUUID().toString()).put("name",required(a,"name")).put("done",false).put("progress",0).put("status","Не начато").put("planDate",a.optString("planDate")).put("responsible",a.optString("responsible")).put("comment",a.optString("comment")));save();break;}
 case "taskUpdate":{JSONObject t=find(project(a.getString("project")).getJSONArray("tasks"),a.getString("id"));int progress=a.getInt("progress");if(progress<0||progress>100)throw new Exception("Прогресс должен быть от 0 до 100%");String status=a.getString("status");if(!Arrays.asList("Не начато","В работе","Приостановлено","Завершено").contains(status))throw new Exception("Неверный статус этапа");t.put("progress",progress).put("status",status).put("done",status.equals("Завершено")).put("planDate",a.optString("planDate")).put("actualDate",a.optString("actualDate")).put("responsible",a.optString("responsible")).put("comment",a.optString("comment"));save();break;}
 case "taskDone":{JSONObject p=project(a.getString("project"));find(p.getJSONArray("tasks"),a.getString("id")).put("done",a.getBoolean("done"));save();break;}
 case "note":{JSONObject p=project(a.getString("project"));p.getJSONArray("notes").put(new JSONObject().put("text",required(a,"text")).put("author",user().getString("name")).put("date",new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.ROOT).format(new Date())));save();break;}
 case "photo":{project(a.getString("project"));pendingProject=a.getString("project");runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,13);});break;}
 case "purchasePhoto":{admin();JSONObject p=project(a.getString("project"));String ref=required(a,"ref");JSONObject purchases=p.optJSONObject("purchases");if(purchases==null||!purchases.has(ref))throw new Exception("Сначала сохраните позицию закупки");String type=a.getString("type");if(!Arrays.asList("Чек","Накладная","Счёт","Документ поставщика").contains(type))throw new Exception("Неверный тип документа");pendingProject=p.getString("id");pendingReceiptRef=ref;pendingReceiptType=type;runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,18);});break;}
 case "backupInfo":{admin();File f=new File(getFilesDir(),"data-previous.enc");result.put("available",f.exists()).put("updated",f.exists()?new Date(f.lastModified()).toString():"");break;}
 case "about":{admin();File f=new File(getFilesDir(),"data-previous.enc");result.put("version",getPackageManager().getPackageInfo(getPackageName(),0).versionName).put("versionCode",getPackageManager().getPackageInfo(getPackageName(),0).versionCode).put("schemaVersion",db.optInt("schemaVersion",1)).put("skuCount",catalog.getJSONArray("materials").length()).put("catalogVersion",catalog.optString("version",catalog.optString("sourceSha256","Встроенный"))).put("backupDate",f.exists()?new Date(f.lastModified()).toString():"Не создан").put("buildType",(getApplicationInfo().flags&android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0?"Debug":"Release").put("serverState",cloudClient==null?"Локальный режим":"Подключён вручную");break;}
 case "integrity":{admin();result.put("report",new JSONObject(diagnostics()));break;}
 case "diagnosticsExport":{admin();File f=new File(getFilesDir(),"errors.log");String report="Arhilab Смета 0.6.2\n"+diagnostics()+"\n"+(f.exists()?new String(java.nio.file.Files.readAllBytes(f.toPath()),StandardCharsets.UTF_8):"Ошибки не записаны\n");exportBytes=report.getBytes(StandardCharsets.UTF_8);runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("text/plain").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"Arhilab-diagnostics.txt");startActivityForResult(i,19);});break;}
 case "restoreAuto":{admin();File f=new File(getFilesDir(),"data-previous.enc");if(!f.exists())throw new Exception("Локальной автокопии пока нет");byte[] all=java.nio.file.Files.readAllBytes(f.toPath());if(all.length<29)throw new Exception("Автокопия повреждена");Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Arrays.copyOfRange(all,0,12)));JSONObject restored=new JSONObject(new String(c.doFinal(Arrays.copyOfRange(all,12,all.length)),StandardCharsets.UTF_8));find(restored.getJSONArray("users"),userId);restored.getJSONArray("projects");db=restored;saveRaw();startSession();break;}
 case "backup":{admin();char[] pw=required(a,"password").toCharArray();try{if(pw.length<12)throw new Exception("Пароль копии: минимум 12 символов");exportBytes=BackupCrypto.encrypt(fullBackupContent().toString().getBytes(StandardCharsets.UTF_8),pw);}finally{Arrays.fill(pw,'\0');}runOnUiThread(()->beginBackupPicker());break;}
 case "restore":case "verifyBackup":{admin();char[] pw=required(a,"password").toCharArray();if(pw.length<12)throw new Exception("Введите пароль резервной копии (от 12 символов)");if(pendingRestorePassword!=null)Arrays.fill(pendingRestorePassword,'\0');pendingRestorePassword=pw;int request=action.equals("verifyBackup")?15:12;runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,request);});break;}
 case "print":{editor();String logo="data:image/png;base64,"+Base64.getEncoder().encodeToString(readBytes(getAssets().open("logo.png")));final String html=a.getString("html").replace("ARHILAB_LOGO_PLACEHOLDER",logo);runOnUiThread(()->{printWeb=new WebView(MainActivity.this);printWeb.getSettings().setJavaScriptEnabled(false);printWeb.getSettings().setAllowFileAccess(false);printWeb.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String url){PrintManager pm=(PrintManager)getSystemService(PRINT_SERVICE);pm.print("Arhilab-КП",v.createPrintDocumentAdapter("Arhilab-КП"),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}});printWeb.loadDataWithBaseURL(null,html,"text/html","UTF-8",null);});break;}
 default:throw new Exception("Неизвестная операция");}
 result.put("ok",true).put("state",state());return result.toString();
 }catch(Exception e){if(before!=null)db=before;recordError(action,e);return "{\"ok\":false,\"error\":"+JSONObject.quote(e.getMessage()==null?"Ошибка операции":e.getMessage())+"}";}}
 }
 void notifyJs(String s){web.evaluateJavascript("alert("+JSONObject.quote(s)+"); refresh();",null);}
 JSONObject readBackup(Uri uri)throws Exception{byte[] contents=readBytes(getContentResolver().openInputStream(uri));if(BackupCrypto.isEncrypted(contents)){if(pendingRestorePassword==null)throw new Exception("Введите пароль копии");try{contents=BackupCrypto.decrypt(contents,pendingRestorePassword);}catch(javax.crypto.AEADBadTagException e){throw new Exception("Неверный пароль или повреждённая копия");}}else if(contents.length==0||contents[0]!='{')throw new Exception("Неизвестный формат файла");JSONObject backup=new JSONObject(new String(contents,StandardCharsets.UTF_8));if(!Arrays.asList("Arhilab-1","Arhilab-2").contains(backup.optString("format")))throw new Exception("Неизвестный формат копии");if(backup.optInt("schemaVersion",1)>DataMigration.CURRENT)throw new Exception("Копия создана более новой версией приложения");return backup;}
 int validateBackup(JSONObject backup)throws Exception{int imageCount=0;JSONArray imported=backup.getJSONArray("projects");for(int i=0;i<imported.length();i++){JSONObject p=imported.getJSONObject(i);if(!p.getString("id").matches("[a-f0-9-]{36}"))throw new Exception("Некорректный ID объекта");p.getString("name");for(String arr:new String[]{"lines","materials","tasks","payments","notes","photos","estimatePhotos"}){JSONArray rows=arr.equals("estimatePhotos")?p.optJSONArray(arr):p.getJSONArray(arr);if(rows==null)continue;for(int j=0;j<rows.length();j++){JSONObject row=rows.getJSONObject(j);if(row.has("id")&&!row.getString("id").matches("[a-f0-9-]{36}"))throw new Exception("Некорректный ID записи");if(arr.equals("photos")||arr.equals("estimatePhotos")){photoBytes(row.optString("data"));imageCount++;}}}JSONArray expenses=p.optJSONArray("expenses");if(expenses!=null)for(int j=0;j<expenses.length();j++)F3Expenses.validate(expenses.getJSONObject(j));}return imageCount;}
 protected void onActivityResult(int req,int result,Intent intent){
  super.onActivityResult(req,result,intent);
  if(req==31||req==32||req==33){if(result!=RESULT_OK){importNotify();return;}final int request=req;final Intent picked=intent;new Thread(()->{try{ArrayList<Uri> uris=new ArrayList<>();if(request==31)uris.add(Uri.parse("content://ru.arhilab.estimate.importcamera/capture"));else if(picked!=null){if(picked.getClipData()!=null)for(int i=0;i<picked.getClipData().getItemCount();i++)uris.add(picked.getClipData().getItemAt(i).getUri());else if(picked.getData()!=null)uris.add(picked.getData());}if(uris.isEmpty())throw new IOException("Файл не выбран");
   synchronized(nativeBridge){editor();JSONObject session=db.getJSONObject("importSession");JSONArray pages=session.getJSONArray("pages");if(pages.length()+uris.size()>100)throw new IOException("Не более 100 страниц");for(Uri uri:uris){String id=UUID.randomUUID().toString();try(InputStream in=getContentResolver().openInputStream(uri)){if(in==null)throw new IOException("Файл недоступен");imports().put(id,in);}boolean pdf=request==33;int count=imports().pageCount(id,pdf);if(pages.length()+count>100)throw new IOException("Не более 100 страниц");String filename=request==31?"Скан "+(pages.length()+1)+".jpg":"Документ "+(pages.length()+1)+(pdf?".pdf":".jpg");try(android.database.Cursor cursor=getContentResolver().query(uri,new String[]{android.provider.OpenableColumns.DISPLAY_NAME},null,null,null)){if(cursor!=null&&cursor.moveToFirst())filename=cursor.getString(0);}for(int i=0;i<count;i++)pages.put(new JSONObject().put("id",UUID.randomUUID().toString()).put("fileId",id).put("name",filename).put("pdf",pdf).put("index",i).put("rotation",0));session.put("sourceType",pdf?"pdf":request==31?"scan":"photo").put("status","draft");}saveRaw();}}
  catch(Exception e){synchronized(nativeBridge){try{JSONObject s=db.optJSONObject("importSession");if(s!=null){s.put("error",e.getMessage());saveRaw();}}catch(Exception ignored){}}}finally{new File(getCacheDir(),"estimate-capture.jpg").delete();importNotify();}},"estimate-import-copy").start();return;}
  if(result!=RESULT_OK||intent==null){if(req==11||req==19)exportBytes=null;if((req==12||req==15)&&pendingRestorePassword!=null){Arrays.fill(pendingRestorePassword,'\0');pendingRestorePassword=null;}return;}
  try{
   if(req==11||req==19){admin();if(exportBytes==null)throw new Exception("Копия не подготовлена");try(OutputStream o=getContentResolver().openOutputStream(intent.getData())){o.write(exportBytes);}exportBytes=null;notifyJs(req==19?"Диагностический отчёт сохранён":"Защищённая копия сохранена");}
   if(req==12||req==15){
    admin();JSONObject backup=readBackup(intent.getData());int imageCount=validateBackup(backup);JSONArray imported=backup.getJSONArray("projects");if(backup.optString("format").equals("Arhilab-2")){JSONArray users=backup.getJSONArray("users");if(users.length()==0)throw new Exception("В копии нет учётных записей");for(int i=0;i<users.length();i++){JSONObject u=users.getJSONObject(i);u.getString("id");u.getString("salt");u.getString("hash");if(u.has("sessionHash"))throw new Exception("Копия содержит сеанс: импорт запрещён");}}
    if(req==15){new AlertDialog.Builder(this).setTitle("Копия прошла проверку").setMessage("Объектов: "+imported.length()+". Фотографий: "+imageCount+". Пароль подходит, структура копии читается. Данные телефона не изменены.").setPositiveButton("Закрыть",null).show();return;}
    new AlertDialog.Builder(this).setTitle("Восстановить данные?").setMessage("Текущие объекты будут заменены. Для полной копии также восстановятся учётные записи; после этого может потребоваться вход по паролю. Перед заменой создаётся зашифрованный снимок базы.").setNegativeButton("Отмена",null).setPositiveButton("Восстановить",(d,w)->{
     JSONObject old=db;File snapshot=new File(getFilesDir(),"data-pre-restore.enc"),dataFile=new File(getFilesDir(),"data.enc");try{admin();JSONObject next=new JSONObject(db.toString());JSONArray fresh=new JSONArray(imported.toString());for(int i=0;i<fresh.length();i++){JSONObject p=fresh.getJSONObject(i);for(String arr:new String[]{"photos","estimatePhotos"}){JSONArray rows=p.optJSONArray(arr);if(rows!=null)for(int j=0;j<rows.length();j++)rows.getJSONObject(j).put("id",UUID.randomUUID().toString());}}
      next.put("projects",fresh);next.remove("f1Sync");if(backup.optString("format").equals("Arhilab-2")){next.put("users",new JSONArray(backup.getJSONArray("users").toString()));JSONObject settings=backup.optJSONObject("settings");if(settings!=null)next.put("settings",settings);}next.put("schemaVersion",backup.optInt("schemaVersion",1));next=DataMigration.migrate(next);if(dataFile.exists())java.nio.file.Files.copy(dataFile.toPath(),snapshot.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);db=next;migratePhotos(db,false);F1SyncLedger.capture(db);saveRaw();if(backup.optString("format").equals("Arhilab-2")){userId=null;new File(getFilesDir(),"session.enc").delete();}notifyJs("Данные восстановлены");
     }catch(Exception e){db=old;try{if(snapshot.exists())java.nio.file.Files.copy(snapshot.toPath(),dataFile.toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);}catch(Exception rollback){recordError("restoreRollback",rollback);}recordError("restore",e);notifyJs("Ошибка восстановления: "+e.getMessage());}
    }).show();
   }
   if(req==16){admin();byte[] bytes=readBytes(getContentResolver().openInputStream(intent.getData()));if(bytes.length>5000000)throw new Exception("Прайс слишком большой");JSONObject updated=new JSONObject(new String(bytes,StandardCharsets.UTF_8));storeCatalog(updated);notifyJs("Прайс обновлён: "+updated.getJSONArray("materials").length()+" SKU");}
   if(req==13||req==14||req==18){
    if(req==14)editor();JSONObject p=project(pendingProject);String collection=req==14?"estimatePhotos":"photos";JSONArray target=p.optJSONArray(collection);if(target==null){target=new JSONArray();p.put(collection,target);}if(req==14&&target.length()>=12)throw new Exception("Не более 12 фото в одной смете");
    android.graphics.BitmapFactory.Options opts=new android.graphics.BitmapFactory.Options();opts.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(intent.getData())){android.graphics.BitmapFactory.decodeStream(in,null,opts);}opts.inSampleSize=1;while(Math.max(opts.outWidth,opts.outHeight)/opts.inSampleSize>(req==14?1200:1600))opts.inSampleSize*=2;opts.inJustDecodeBounds=false;
    android.graphics.Bitmap bitmap;try(InputStream in=getContentResolver().openInputStream(intent.getData())){bitmap=android.graphics.BitmapFactory.decodeStream(in,null,opts);}if(bitmap==null)throw new Exception("Не удалось открыть фото");ByteArrayOutputStream bytes=new ByteArrayOutputStream();bitmap.compress(android.graphics.Bitmap.CompressFormat.JPEG,req==14?72:80,bytes);bitmap.recycle();if(bytes.size()>1500000)throw new Exception("Фото слишком большое: выберите изображение меньшего размера");
    String id=UUID.randomUUID().toString();photos().put(id,bytes.toByteArray());JSONObject record=new JSONObject().put("id",id).put("date",new java.text.SimpleDateFormat("dd.MM.yyyy HH:mm",Locale.ROOT).format(new Date()));if(req==18)record.put("purchaseRef",pendingReceiptRef).put("documentType",pendingReceiptType);target.put(record);save();notifyJs(req==18?"Документ закупки добавлен":req==14?"Фото добавлено в смету":"Фото добавлено");
   }
  }catch(Exception e){notifyJs("Ошибка: "+e.getMessage());}
  finally{if((req==12||req==15)&&pendingRestorePassword!=null){Arrays.fill(pendingRestorePassword,'\0');pendingRestorePassword=null;}if(req==11||req==19)exportBytes=null;}
 }
 @Override public void onBackPressed(){web.evaluateJavascript("back()",null);}
 @Override protected void onDestroy(){closeCloud();super.onDestroy();}
}
