exports.up = (pgm) => {
  pgm.sql(`
    CREATE TABLE organizations (id uuid PRIMARY KEY, name text NOT NULL CHECK (length(trim(name)) > 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE users (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), display_name text NOT NULL, email text, role text NOT NULL CHECK (role IN ('admin','manager','worker')), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id,id), UNIQUE (organization_id,email));
    CREATE TABLE devices (id uuid PRIMARY KEY, organization_id uuid NOT NULL, user_id uuid NOT NULL, label text, revoked_at timestamptz, last_seen_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id,id), FOREIGN KEY (organization_id,user_id) REFERENCES users(organization_id,id));
    CREATE TABLE projects (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id));
    CREATE TABLE estimates (id uuid PRIMARY KEY, organization_id uuid NOT NULL, project_id uuid NOT NULL, name text NOT NULL, revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id), FOREIGN KEY (organization_id,project_id) REFERENCES projects(organization_id,id));
    CREATE TABLE estimate_items (id uuid PRIMARY KEY, organization_id uuid NOT NULL, estimate_id uuid NOT NULL, title text NOT NULL, quantity numeric(18,4) NOT NULL DEFAULT 0, unit text, revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id), FOREIGN KEY (organization_id,estimate_id) REFERENCES estimates(organization_id,id));
    CREATE TABLE materials (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, unit text, revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id));
    CREATE TABLE stages (id uuid PRIMARY KEY, organization_id uuid NOT NULL, project_id uuid NOT NULL, name text NOT NULL, position integer NOT NULL DEFAULT 0, revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id), FOREIGN KEY (organization_id,project_id) REFERENCES projects(organization_id,id));
    CREATE TABLE payments (id uuid PRIMARY KEY, organization_id uuid NOT NULL, project_id uuid NOT NULL, amount numeric(18,2) NOT NULL CHECK (amount >= 0), currency char(3) NOT NULL, paid_at timestamptz, revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id), FOREIGN KEY (organization_id,project_id) REFERENCES projects(organization_id,id));
    CREATE TABLE tasks (id uuid PRIMARY KEY, organization_id uuid NOT NULL, project_id uuid NOT NULL, assignee_id uuid, title text NOT NULL, status text NOT NULL DEFAULT 'open', revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id), FOREIGN KEY (organization_id,project_id) REFERENCES projects(organization_id,id), FOREIGN KEY (organization_id,assignee_id) REFERENCES users(organization_id,id));
    CREATE TABLE photos (id uuid PRIMARY KEY, organization_id uuid NOT NULL, project_id uuid NOT NULL, storage_key text NOT NULL, revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id), FOREIGN KEY (organization_id,project_id) REFERENCES projects(organization_id,id));
    CREATE TABLE documents (id uuid PRIMARY KEY, organization_id uuid NOT NULL, project_id uuid NOT NULL, storage_key text NOT NULL, revision bigint NOT NULL DEFAULT 0 CHECK (revision >= 0), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz, UNIQUE (organization_id,id), FOREIGN KEY (organization_id,project_id) REFERENCES projects(organization_id,id));
    CREATE TABLE sync_operations (id uuid PRIMARY KEY, organization_id uuid NOT NULL, device_id uuid NOT NULL, entity_type text NOT NULL, entity_id uuid NOT NULL, operation_type text NOT NULL, base_revision bigint NOT NULL CHECK (base_revision >= 0), resulting_revision bigint CHECK (resulting_revision >= 0), status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','applied','conflict','retry','failed')), idempotency_key text NOT NULL, attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0), next_retry_at timestamptz, conflict_metadata jsonb, occurred_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE (organization_id,id), UNIQUE (organization_id,idempotency_key), FOREIGN KEY (organization_id,device_id) REFERENCES devices(organization_id,id));
    CREATE TABLE audit_logs (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), user_id uuid, device_id uuid, action text NOT NULL, entity_type text NOT NULL, entity_id uuid, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, occurred_at timestamptz NOT NULL DEFAULT now(), FOREIGN KEY (organization_id,user_id) REFERENCES users(organization_id,id), FOREIGN KEY (organization_id,device_id) REFERENCES devices(organization_id,id));
    CREATE INDEX ON devices (organization_id,user_id);
    CREATE INDEX ON estimates (organization_id,project_id);
    CREATE INDEX ON estimate_items (organization_id,estimate_id);
    CREATE INDEX ON stages (organization_id,project_id);
    CREATE INDEX ON payments (organization_id,project_id);
    CREATE INDEX ON tasks (organization_id,project_id);
    CREATE INDEX ON photos (organization_id,project_id);
    CREATE INDEX ON documents (organization_id,project_id);
    CREATE INDEX ON sync_operations (organization_id,status,next_retry_at);
    CREATE INDEX ON audit_logs (organization_id,occurred_at);
  `);
};
exports.down = (pgm) => {
  pgm.sql('DROP TABLE audit_logs, sync_operations, documents, photos, tasks, payments, stages, materials, estimate_items, estimates, projects, devices, users, organizations;');
};
