const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.join(__dirname,'../assets');const legacy=fs.readFileSync(path.join(root,'import-alpha4.js'),'utf8').split('let import4Session=')[0];const next=fs.readFileSync(path.join(root,'import-layout-alpha5.js'),'utf8');const ctx={module:{exports:{}},console};vm.runInNewContext(legacy+'\n'+next+'\nmodule.exports={Import4,Import5}',ctx);const {Import5:p}=ctx.module.exports;
const page=(text,n=1)=>({page:n,text});const works=[{id:'1',name:'Шпаклёвка стен под покраску',price:900}];const parse=(text)=>p.parse([page(text)],works);
assert.equal(parse('Шпаклёвка стен').rows.length,0,'bare text is never an item');
assert.equal(parse('Стоимость материалов может изменяться').rows.length,0);
assert.equal(parse('Демонтаж').visualRows[0].type,'SECTION_HEADER');
assert.equal(parse('Итого: 35000 ₽').visualRows[0].type,'TOTAL');
assert.equal(parse('Примечание: цены ориентировочные').visualRows[0].type,'NOTE');
let one=parse('Шпаклёвка стен | м² | 50 | 700 | 35000');assert.equal(one.rows.length,1);assert.equal(one.rows[0].amount,35000);assert.equal(one.rows[0].confidence,'HIGH');
let multi=parse('Демонтаж\n№  Наименование  Ед.  Количество  Цена  Сумма\n1  Демонтаж перегородки  м²  20  500  10000\nНаименование  Ед.  Количество  Цена  Сумма\nИтого  10000');assert.equal(multi.rows.length,1);assert.equal(multi.rows[0].section,'Демонтаж');assert.equal(multi.total,10000);
let incomplete=parse('Шпаклёвка стен | м2 | 50 | 700');assert.equal(incomplete.rows.length,1);assert.equal(incomplete.rows[0].needsReview,true);
let unknown=parse('Неизвестная работа | шт. | 1 | 850 | 850');assert.equal(unknown.rows.length,1);assert.equal(unknown.rows[0].candidate,null);
let wrapped=parse('Наименование  Ед.  Количество  Цена  Сумма\nМонтаж перегородки\nиз ГКЛ\nв два слоя | м² | 20 | 1200 | 24000');assert.equal(wrapped.rows.length,1);assert.equal(wrapped.rows[0].name,'Монтаж перегородки из ГКЛ в два слоя');
let prose=parse('Стоимость материалов может изменяться\nШпаклёвка стен | м² | 50 | 700 | 35000');assert.equal(prose.rows.length,1);assert.equal(prose.rows[0].name,'Шпаклёвка стен');assert.equal(prose.visualRows[0].type,'PLAIN_TEXT');
let words=['Шпаклёвка','стен','под','покраску','м²','50','700','35000'].map((text,i)=>({text,x:i*105,y:i%2?101:100,width:95,height:20,order:i}));let geom=p.parse([{page:1,words,text:words.map(w=>w.text).join('\n')}],works);assert.equal(geom.rows.length,1);assert.equal(geom.rows[0].name,'Шпаклёвка стен под покраску');
assert.equal(p.parse([{page:1,words:words.map(w=>({...w,confidence:30}))}],works).rows[0].confidence,'LOW');
let big=p.parse(Array.from({length:20},(_,n)=>page('Наименование  Ед.  Количество  Цена  Сумма\n'+Array.from({length:10},(_,i)=>`${n*10+i+1}  Работа ${i+1}  шт.  2  10  20`).join('\n')+(n===19?'\nИтого 4000':''),n+1)),works);assert.equal(big.rows.length,200);assert.equal(big.total,4000);
assert.equal(p.number('1.250,50'),1250.5);assert.equal(p.unit('кв.м'),'м²');assert.equal(p.unit('м.кв'),'м²');assert.equal(p.unit('комплект'),'компл.');
console.log('Alpha5 layout: plain text, geometry, sections, totals, multiline, 200 rows and repeated headers OK');
