const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
const {calc,round}=require('../assets/core.js');
const catalog=require('../assets/catalog.json');
const base=path.resolve(__dirname,'../assets/index.html');
let count=0;
function check(name,fn){return Promise.resolve().then(fn).then(()=>{count++;console.log(`${count}. PASS — ${name}`)});}
const projects=[{id:'6f57831c-d3bb-4cd7-b48b-732bddc93e13',name:'Объект А',address:'Москва',status:'В работе',assigned:'worker1',client:'Иванов',delivery:0,discount:0,lines:[{id:'line1',name:'Штукатурка',unit:'м²',qty:2,coef:1,price:1200,cost:700,materials:[],autoMaterial:false}],materials:[],tasks:[{id:'task1',name:'Проверка',done:false}],payments:[{id:'pay1',amount:500,kind:'income',date:'2026-09-24',note:'Аванс'},{id:'pay2',amount:100,kind:'expense',date:'2026-09-24',note:'Закупка'}],notes:[],photos:[]}];
function state(role){let user={id:role==='worker'?'worker1':role,name:role==='admin'?'Администратор':'Сотрудник',login:role,role};let ps=JSON.parse(JSON.stringify(projects));if(role==='manager')ps.forEach(p=>{p.lines.forEach(l=>delete l.cost);p.payments=p.payments.filter(x=>x.kind==='income')});if(role==='worker')ps=ps.map(p=>({id:p.id,name:p.name,address:p.address,status:p.status,assigned:p.assigned,tasks:p.tasks,notes:p.notes,photos:p.photos}));return {user,users:[user],projects:ps};}
function visibleCatalog(role){let c=JSON.parse(JSON.stringify(catalog));if(role==='worker')return {works:[],materials:[]};if(role==='manager'){c.works.forEach(w=>{delete w.cost;Object.values(w.tiers).forEach(k=>delete k.materialCost)});c.materials.forEach(m=>delete m.cost)}return c;}
(async()=>{
 await check('Каталог: 371 работ, 254 материала и 110 связок',()=>{assert.equal(catalog.works.length,371);assert.equal(catalog.materials.length,254);assert.equal(catalog.works.filter(x=>x.tiers.standard.materialIds.length>0).length,110)});
 await check('Одна работа: выручка, оплата исполнителю и маржа',()=>{let c=calc({lines:[{qty:10,coef:1,price:100,cost:60}]});assert.deepEqual([c.total,c.labor,c.gross,c.margin],[1000,600,400,40])});
 await check('Сложность 1,5 и скидка отражаются в прибыли',()=>{let c=calc({lines:[{qty:10,coef:1.5,price:100,cost:60}],discount:100});assert.deepEqual([c.work,c.labor,c.total,c.profit],[1500,900,1400,500])});
 await check('Комплект материалов по умолчанию выключен; после включения +8%',()=>{let l={qty:2,coef:1,price:100,cost:60,materialPrice:108,materialCost:100,autoMaterial:false};assert.equal(calc({lines:[l]}).mat,0);l.autoMaterial=true;let c=calc({lines:[l]});assert.deepEqual([c.mat,c.matCost,c.total],[216,200,416])});
 await check('Работает смета более чем из 20 строк',()=>{let l={qty:1,coef:1,price:100,cost:60};let c=calc({lines:Array(25).fill(l)});assert.deepEqual([c.work,c.labor,c.profit],[2500,1500,1000])});
 await check('Платежи: аванс, расход и остаток по смете',()=>{let c=calc({lines:[{qty:1,coef:1,price:1000,cost:600}],payments:[{kind:'income',amount:400},{kind:'expense',amount:100}]});assert.deepEqual([c.paid,c.spent,c.balance,c.cash],[400,100,600,300])});
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--no-sandbox']});
 async function page(role){let p=await browser.newPage({viewport:{width:412,height:915}});p.setDefaultTimeout(6000);let errors=[];p.on('pageerror',e=>errors.push(e.message));await p.addInitScript(({role,s,c})=>{window.Native={call:(a,raw)=>{if(a==='status')return JSON.stringify({ok:true,setup:false});if(a==='login'||a==='state')return JSON.stringify({ok:true,state:s});if(a==='catalog')return JSON.stringify({ok:true,state:s,catalog:c});if(a==='photoData')return JSON.stringify({ok:true,state:s,photos:[]});if(a==='print'){window.documentHtml=JSON.parse(raw).html;return JSON.stringify({ok:true,state:s})}return JSON.stringify({ok:true,state:s})}}},{role,s:state(role),c:visibleCatalog(role)});await p.goto('file://'+base);await p.fill('[name=login]',role);await p.fill('[name=password]','test-password');await p.click('button[type=submit]');await p.getByText('Объект А').first().waitFor();return {p,errors};}
 await check('Администратор входит, видит объект и экономику',async()=>{let {p,errors}=await page('admin');await p.getByText('Объект А').click();await p.locator('.tabs').getByText('Экономика').click();assert.match(await p.locator('#detail').innerText(),/Плановая прибыль/);assert.equal(errors.length,0);await p.close()});
 await check('КП содержит клиентские цены без внутренних расценок',async()=>{let {p}=await page('admin');await p.getByText('Объект А').click();await p.locator('.tabs').getByText('Документы').click();await p.getByText('Сохранить КП в PDF').click();let html=await p.evaluate(()=>window.documentHtml);assert.match(html,/2\s400,00/);assert.doesNotMatch(html,/700,00|Исполнителю|Валовая прибыль/);await p.close()});
 await check('Менеджер видит клиентскую смету без экономики и затрат',async()=>{let {p,errors}=await page('manager');await p.getByText('Объект А').click();assert.equal(await p.locator('.tabs').getByText('Экономика').count(),0);assert.doesNotMatch(await p.locator('#app').innerText(),/Исполнителю|Закупка материалов|700,00/);assert.equal(errors.length,0);await p.close()});
 await check('Рабочий видит этапы объекта без финансовых разделов',async()=>{let {p,errors}=await page('worker');await p.getByText('Этапы, фото и замечания',{exact:true}).click();let tabs=await p.locator('.tabs').innerText();assert.match(tabs,/Этапы/);assert.doesNotMatch(tabs,/Смета|Материалы|Экономика|Платежи|Документы/);assert.equal(errors.length,0);await p.close()});
 await browser.close();console.log('Всего: '+count+' из 10 PASS. Интерфейс: имитация Android bridge, не устройство.');
})().catch(e=>{console.error(e);process.exit(1)});
